'use strict';

/**
 * GENERATED by scripts/build-fsa-ref.mjs from js/whollar-fsa-cities.js. Do NOT edit by hand.
 * Run the generator and commit the result, or the --check gate reports STALE.
 *
 * The FSA reference, server side: 1652 forward sortation areas with the
 * municipality and province each one sits in.
 *
 * Source: GeoNames.org CA.txt (http://download.geonames.org/export/zip/CA.zip)
 * License: CC BY 4.0 -- https://creativecommons.org/licenses/by/4.0/
 * Built from that export on 2026-08-07.
 *
 * By province: AB=155, BC=192, MB=67, NB=111, NL=35, NS=77, NT=3, NU=3, ON=527, PE=7, QC=422, SK=50, YT=3.
 *
 * WHAT IT IS FOR. Two things and no others:
 *
 *   has(fsa)     the operator gate. routes/admin.js refuses an FSA that is not
 *                in here when a campaign's coverage is edited, because an FSA
 *                nobody lives in is a cohort nobody can join and it looks
 *                identical to a cohort nobody wants.
 *
 *   lookup(fsa)  the rail's ORDER, via geo.nearbyTier: same city, then same
 *                province, then everything else. Ordering only. It never
 *                grants or denies a join, and a missing row costs a campaign
 *                its place in the sort and nothing more.
 *
 * IT IS NOT CHECKED AGAINST A MEMBER'S OWN POSTAL CODE, deliberately. This is
 * a best-effort free-tier mapping, not the Canada Post file, and refusing a
 * household an account because a free dataset has not heard of its FSA would
 * be this file deciding something it is not good enough to decide. A
 * structurally valid FSA that matches no campaign simply yields no
 * eligibility, which is the honest answer and already the common one.
 *
 * INHERITED CAVEATS, from js/whollar-fsa-cities.coverage.txt: GeoNames groups
 * some genuinely distinct municipalities under one metro label (North
 * Vancouver and West Vancouver FSAs both report "Vancouver"), and a few rural
 * FSAs report a district rather than a town. Both affect the city tier of the
 * rail's ordering and nothing else in this stack.
 */

/* "City|PROVINCE", packed: two fields per FSA across 1652 rows is 3300
   short strings on every cold start otherwise, for a table read a few times a
   request. Split once, on the lookup that needs it. */
const FSA = {
  A0A:"Ferryland|NL",A0B:"Western|NL",A0C:"Bonavista|NL",A0E:"Marystown|NL",A0G:"Lewisporte|NL",A0H:"Bishops Falls|NL",A0J:"Springdale|NL",A0K:"Mary's Harbour|NL",A0L:"Western|NL",A0M:"Channel-Port aux Basques|NL",
  A0N:"St. George's|NL",A0P:"Happy Valley-Goose Bay|NL",A0R:"Churchill Falls|NL",A1A:"St. John's|NL",A1B:"St. John's|NL",A1C:"St. John's|NL",A1E:"St. John's|NL",A1G:"St. John's|NL",A1H:"St. John's|NL",A1K:"Torbay|NL",
  A1L:"Paradise|NL",A1M:"Portugal Cove-St. Philips|NL",A1N:"Mount Pearl|NL",A1S:"Goulds|NL",A1V:"Gander|NL",A1W:"Manuels|NL",A1X:"Conception Bay|NL",A1Y:"Carbonear|NL",A2A:"Grand Falls|NL",A2B:"Windsor|NL",
  A2H:"Corner Brook|NL",A2N:"Stephenville|NL",A2V:"Labrador City|NL",A5A:"Clarenville|NL",A8A:"Deer Lake|NL",B0C:"Dingwall|NS",B0E:"Baddeck|NS",B0H:"Havre Boucher|NS",B0J:"Lunenburg|NS",B0K:"Pictou|NS",
  B0L:"River Hébert|NS",B0M:"Springhill|NS",B0N:"Shubenacadie|NS",B0P:"Kingston|NS",B0R:"New Germany|NS",B0S:"Middleton|NS",B0T:"Shelburne|NS",B0V:"Digby|NS",B0W:"Weymouth|NS",B1A:"Glace Bay|NS",
  B1B:"Port Morien|NS",B1C:"Louisbourg|NS",B1E:"Reserve Mines|NS",B1G:"Dominion|NS",B1H:"New Waterford|NS",B1J:"East Bay|NS",B1K:"Marion Bridge|NS",B1L:"Sydney|NS",B1M:"Sydney|NS",B1N:"Sydney|NS",
  B1P:"Sydney|NS",B1R:"Sydney|NS",B1S:"Sydney|NS",B1T:"Christmas Island|NS",B1V:"North Sydney North|NS",B1W:"Eskasoni|NS",B1X:"Big Bras d'Or|NS",B1Y:"Alder Point|NS",B2A:"North Sydney South Central|NS",B2C:"Iona|NS",
  B2E:"Loch Lomond|NS",B2G:"Antigonish|NS",B2H:"New Glasgow|NS",B2J:"Fourchu|NS",B2N:"Truro|NS",B2R:"Waverley|NS",B2S:"Lantz|NS",B2T:"Enfield|NS",B2V:"Dartmouth|NS",B2W:"Dartmouth|NS",
  B2X:"Dartmouth|NS",B2Y:"Dartmouth|NS",B2Z:"Dartmouth|NS",B3A:"Dartmouth|NS",B3B:"Dartmouth|NS",B3E:"Porters Lake|NS",B3G:"Eastern Passage|NS",B3H:"Halifax|NS",B3J:"Halifax|NS",B3K:"Halifax|NS",
  B3L:"Halifax|NS",B3M:"Halifax|NS",B3N:"Halifax|NS",B3P:"Halifax|NS",B3R:"Halifax|NS",B3S:"Halifax|NS",B3T:"Lakeside|NS",B3V:"Harrietsfield|NS",B3Z:"Tantallon|NS",B4A:"Bedford|NS",
  B4B:"Bedford|NS",B4C:"Lower Sackville|NS",B4E:"Lower Sackville|NS",B4G:"Lower Sackville|NS",B4H:"Amherst|NS",B4N:"Kentville|NS",B4P:"Wolfville|NS",B4R:"Coldbrook|NS",B4V:"Bridgewater|NS",B5A:"Yarmouth|NS",
  B6L:"Truro|NS",B9A:"Port Hawkesbury|NS",C0A:"Elmira|PE",C0B:"Prince County|PE",C1A:"Charlottetown|PE",C1B:"Stratford|PE",C1C:"Charlottetown|PE",C1E:"Charlottetown|PE",C1N:"Summerside|PE",E1A:"Dieppe Moncton East|NB",
  E1B:"Riverview|NB",E1C:"Moncton|NB",E1E:"Moncton|NB",E1G:"Moncton|NB",E1H:"Lakeville, Shediac Bridge|NB",E1J:"Coverdale|NB",E1N:"Miramichi|NB",E1V:"Miramichi|NB",E1W:"Caraquet|NB",E1X:"Tracadie-Sheila|NB",
  E2A:"Bathurst|NB",E2E:"Rothesay, Quispamsis|NB",E2G:"Quispamsis|NB",E2H:"Saint John|NB",E2J:"Saint John|NB",E2K:"Saint John|NB",E2L:"Saint John|NB",E2M:"Saint John|NB",E2N:"Saint John|NB",E2P:"Saint John|NB",
  E2R:"Saint John|NB",E2S:"Saint John|NB",E2V:"Oromocto|NB",E3A:"Fredericton|NB",E3B:"Fredericton|NB",E3C:"Fredericton|NB",E3E:"Kingsclear|NB",E3G:"Fredericton|NB",E3L:"St. Stephen|NB",E3N:"Campbellton|NB",
  E3V:"Edmundston|NB",E3Y:"Grand Falls|NB",E3Z:"Grand Falls|NB",E4A:"Bathurst|NB",E4B:"Minto|NB",E4C:"Youngs Cove|NB",E4E:"Sussex|NB",E4G:"Smiths Creek|NB",E4H:"Hillsborough|NB",E4J:"Salisbury|NB",
  E4K:"Dorchester|NB",E4L:"Sackville|NB",E4M:"Bayfield|NB",E4N:"Cap-Pelé|NB",E4P:"Shediac|NB",E4R:"Cocagne|NB",E4S:"Bouctouche|NB",E4T:"Bass River|NB",E4V:"Saint-Antoine|NB",E4W:"Richibucto|NB",
  E4X:"St-Louis-de-Kent|NB",E4Y:"Rogersville|NB",E4Z:"Petitcodiac|NB",E5A:"Moores Mills|NB",E5B:"St. Andrews|NB",E5C:"St. George|NB",E5E:"Campobello Island|NB",E5G:"Grand|NB",E5H:"Pennfield|NB",E5J:"Lepreau|NB",
  E5K:"Grand|NB",E5L:"Fredericton Junction|NB",E5M:"Gagetown|NB",E5N:"Hampton|NB",E5P:"Apohaqui|NB",E5R:"St. Martins|NB",E5S:"Kingston|NB",E5T:"Norton|NB",E5V:"Deer Island|NB",E6A:"Boiestown|NB",
  E6B:"Stanley|NB",E6C:"Durham Bridge|NB",E6E:"Millville|NB",E6G:"Nackawic|NB",E6H:"Canterbury|NB",E6J:"McAdam|NB",E6K:"Harvey|NB",E6L:"Burtts Corner|NB",E7A:"Baker Brook|NB",E7B:"Saint-Jacques|NB",
  E7C:"Saint-Basile|NB",E7E:"Saint-Leonard|NB",E7G:"Plaster Rock|NB",E7H:"Perth-Andover|NB",E7J:"Bath|NB",E7K:"Centreville|NB",E7L:"Florenceville|NB",E7M:"Woodstock|NB",E7N:"Debec|NB",E7P:"Hartland|NB",
  E8A:"Saint-Quentin|NB",E8B:"Kedgwick|NB",E8C:"Dalhousie|NB",E8E:"Balmoral|NB",E8G:"Belledune|NB",E8J:"Petit-Rocher|NB",E8K:"Beresford|NB",E8L:"Allardville|NB",E8M:"Saint-Isidore|NB",E8N:"Grande-Anse|NB",
  E8P:"Inkerman|NB",E8R:"Paquetville|NB",E8S:"Shippagan|NB",E8T:"Lamèque|NB",E9A:"Baie-Sainte-Anne|NB",E9B:"Blackville|NB",E9C:"Doaktown|NB",E9E:"Red Bank|NB",E9G:"Neguac|NB",E9H:"Brantville|NB",
  G0A:"Capitale-Nationale|QC",G0B:"Cap-aux-Meules|QC",G0C:"New Richmond|QC",G0E:"Grande-Vallée|QC",G0G:"Côte-Nord|QC",G0H:"Baie-Trinité|QC",G0J:"Causapscal|QC",G0K:"Sainte-Luce|QC",G0L:"Trois-Pistoles|QC",G0M:"Région de|QC",
  G0N:"Disraeli|QC",G0P:"Centre-du-Québec|QC",G0R:"La Pocatière|QC",G0S:"Saint-Joseph-De-Beauce|QC",G0T:"Forestville|QC",G0V:"Alouette|QC",G0W:"Région de|QC",G0X:"Mauricie|QC",G0Y:"Nantes|QC",G0Z:"Centre-du-Québec|QC",
  G1A:"Capitale-Nationale|QC",G1B:"Beauport|QC",G1C:"Beauport|QC",G1E:"Beauport|QC",G1G:"Jean-Talon Southeast|QC",G1H:"Charlesbourg South|QC",G1J:"Capitale-Nationale|QC",G1K:"Capitale-Nationale|QC",G1L:"Capitale-Nationale|QC",G1M:"Capitale-Nationale|QC",
  G1N:"Capitale-Nationale|QC",G1P:"Capitale-Nationale|QC",G1R:"Capitale-Nationale|QC",G1S:"Capitale-Nationale|QC",G1T:"Capitale-Nationale|QC",G1V:"Sainte-Foy|QC",G1W:"Sainte-Foy|QC",G1X:"Sainte-Foy|QC",G1Y:"Cap-Rouge|QC",G2A:"Loretteville|QC",
  G2B:"Loretteville|QC",G2C:"Capitale-Nationale|QC",G2E:"Capitale-Nationale|QC",G2G:"L'Ancienne-Lorette Southwest|QC",G2J:"Capitale-Nationale|QC",G2K:"Capitale-Nationale|QC",G2L:"Charlesbourg North|QC",G2M:"Jean-Talon|QC",G2N:"Jean-Talon|QC",G3A:"St-Augustin-De-Desmaures|QC",
  G3B:"Capitale-Nationale|QC",G3C:"Capitale-Nationale|QC",G3E:"Saint-Émile|QC",G3G:"Lac-Saint-Charles|QC",G3H:"Capitale-Nationale|QC",G3J:"Val-Bélair|QC",G3K:"Val-Bélair|QC",G3L:"Saint-Raymond|QC",G3M:"Capitale-Nationale|QC",G3N:"Capitale-Nationale|QC",
  G3S:"Capitale-Nationale|QC",G3Z:"Capitale-Nationale|QC",G4A:"Capitale-Nationale|QC",G4R:"Sept-Îles Southeast|QC",G4S:"Côte-Nord|QC",G4T:"Les Îles-De-La-Madeleine|QC",G4V:"Sainte-Anne-Des-Monts|QC",G4W:"Bas-Saint-Laurent|QC",G4X:"Gaspésie-Îles-de-la-Madeleine|QC",G4Z:"Baie-Comeau Northeast|QC",
  G5A:"Capitale-Nationale|QC",G5B:"Côte-Nord|QC",G5C:"Baie-Comeau Southwest|QC",G5H:"Bas-Saint-Laurent|QC",G5J:"Bas-Saint-Laurent|QC",G5L:"Bas-Saint-Laurent|QC",G5M:"Bas-Saint-Laurent|QC",G5N:"Bas-Saint-Laurent|QC",G5R:"Bas-Saint-Laurent|QC",G5T:"Degelis|QC",
  G5V:"Chaudière-Appalaches|QC",G5X:"Chaudière-Appalaches|QC",G5Y:"Chaudière-Appalaches|QC",G5Z:"Chaudière-Appalaches|QC",G6A:"Chaudière-Appalaches|QC",G6B:"Lac-Megantic|QC",G6C:"Pintendre|QC",G6E:"Chaudière-Appalaches|QC",G6G:"Chaudière-Appalaches|QC",G6H:"Black Lake|QC",
  G6J:"Saint-Etienne-De-Lauzon|QC",G6K:"Saint-Redempteur|QC",G6L:"Centre-du-Québec|QC",G6P:"Centre-du-Québec|QC",G6R:"Victoriaville|QC",G6S:"Victoriaville|QC",G6T:"Centre-du-Québec|QC",G6V:"Chaudière-Appalaches|QC",G6W:"Chaudière-Appalaches|QC",G6X:"Charny|QC",
  G6Y:"Chaudière-Appalaches|QC",G6Z:"Saint-Jean-Chrysostome|QC",G7A:"Saint-Nicolas|QC",G7B:"La Baie|QC",G7G:"Chicoutimi|QC",G7H:"Chicoutimi|QC",G7J:"Chicoutimi|QC",G7K:"Chicoutimi|QC",G7N:"Laterrière|QC",G7P:"Saguenay/Lac-Saint-Jean|QC",
  G7S:"Jonquière|QC",G7T:"Jonquière|QC",G7X:"Jonquière|QC",G7Y:"Jonquière|QC",G7Z:"Jonquière|QC",G8A:"Jonquière West|QC",G8B:"Saguenay/Lac-Saint-Jean|QC",G8C:"Saguenay/Lac-Saint-Jean|QC",G8E:"Saguenay/Lac-Saint-Jean|QC",G8G:"Métabetchouan-Lac-a-la-Croix|QC",
  G8H:"Saguenay/Lac-Saint-Jean|QC",G8J:"Saguenay/Lac-Saint-Jean|QC",G8K:"Saguenay/Lac-Saint-Jean|QC",G8L:"Saguenay/Lac-Saint-Jean|QC",G8M:"Saguenay/Lac-Saint-Jean|QC",G8N:"Saguenay/Lac-Saint-Jean|QC",G8P:"Nord-du-Québec|QC",G8T:"Cap-de-la-Madeleine|QC",G8V:"Cap-de-la-Madeleine|QC",G8W:"Cap-de-la-Madeleine|QC",
  G8Y:"Trois-Rivières|QC",G8Z:"Trois-Rivières|QC",G9A:"Trois-Rivières|QC",G9B:"Trois-Rivières|QC",G9C:"Trois-Rivières|QC",G9H:"Becancour|QC",G9N:"Shawinigan|QC",G9P:"Shawinigan|QC",G9R:"Shawinigan|QC",G9T:"Grand-Mère|QC",
  G9X:"Mauricie|QC",H0H:"Santa Claus|QC",H0M:"Akwesasne|QC",H1A:"Pointe-Aux-Trembles|QC",H1B:"Montreal|QC",H1C:"Rivière-des-Prairies Northeast|QC",H1E:"Rivière-Des-Prairies Southwest|QC",H1G:"Montreal|QC",H1H:"Montreal|QC",H1J:"Anjou|QC",
  H1K:"Anjou|QC",H1L:"Mercier|QC",H1M:"Mercier|QC",H1N:"Mercier|QC",H1P:"Saint-Léonard|QC",H1R:"Saint-Léonard|QC",H1S:"Saint-Léonard|QC",H1T:"Rosemont|QC",H1V:"Maisonneuve|QC",H1W:"Hochelaga|QC",
  H1X:"Rosemont|QC",H1Y:"Rosemont|QC",H1Z:"Saint-Michel West|QC",H2A:"Saint-Michel East|QC",H2B:"Ahuntsic|QC",H2C:"Ahuntsic|QC",H2E:"Villeray|QC",H2G:"Petite-Patrie|QC",H2H:"Plateau Mont-Royal|QC",H2J:"Plateau Mont-Royal|QC",
  H2K:"Centre-Sud North|QC",H2L:"Centre-Sud South|QC",H2M:"Ahuntsic|QC",H2N:"Ahuntsic|QC",H2P:"Villeray|QC",H2R:"Villeray|QC",H2S:"Petite-Patrie|QC",H2T:"Plateau Mont-Royal|QC",H2V:"Outremont|QC",H2W:"Plateau Mont-Royal|QC",
  H2X:"Plateau Mont-Royal|QC",H2Y:"Montreal|QC",H2Z:"Montreal|QC",H3A:"Montreal|QC",H3B:"Montreal|QC",H3C:"Includes Île Notre-Dame & Île Sainte-Hélène|QC",H3E:"L'Île-Des-Soeurs|QC",H3G:"Montreal|QC",H3H:"Montreal|QC",H3J:"Petite-Bourgogne|QC",
  H3K:"Pointe-Saint-Charles|QC",H3L:"Ahuntsic Southwest|QC",H3M:"Cartierville Northeast|QC",H3N:"Parc-Extension|QC",H3P:"Mount Royal|QC",H3R:"Mount Royal|QC",H3S:"Côte-des-Neiges|QC",H3T:"Côte-des-Neiges|QC",H3V:"Côte-des-Neiges|QC",H3W:"Côte-des-Neiges|QC",
  H3X:"Montréal|QC",H3Y:"Montréal|QC",H3Z:"Montréal|QC",H4A:"Notre-Dame-de-Grâce|QC",H4B:"Notre-Dame-de-Grâce|QC",H4C:"Saint-Henri|QC",H4E:"Ville Émard|QC",H4G:"Verdun|QC",H4H:"Verdun|QC",H4J:"Cartierville|QC",
  H4K:"Cartierville|QC",H4L:"Saint-Laurent|QC",H4M:"Saint-Laurent|QC",H4N:"Saint-Laurent|QC",H4P:"Mount Royal South|QC",H4R:"Saint-Laurent|QC",H4S:"Saint-Laurent|QC",H4T:"Saint-Laurent|QC",H4V:"Côte-Saint-Luc East|QC",H4W:"Montréal|QC",
  H4X:"Montreal|QC",H4Y:"Dorval Central|QC",H4Z:"Tour de la Bourse|QC",H5A:"Place|QC",H5B:"Place|QC",H7A:"Duvernay-Est|QC",H7B:"Saint-Franþois|QC",H7C:"Saint-Vincent-de-Paul|QC",H7E:"Duvernay|QC",H7G:"Pont-Viau|QC",
  H7H:"Auteuil|QC",H7J:"Auteuil|QC",H7K:"Auteuil|QC",H7L:"Sainte-Rose|QC",H7M:"Vimont|QC",H7N:"Laval|QC",H7P:"Fabreville|QC",H7R:"Laval|QC",H7S:"Chomedey|QC",H7T:"Chomedey|QC",
  H7V:"Chomedey|QC",H7W:"Chomedey|QC",H7X:"Sainte-Dorothée|QC",H7Y:"Îles-Laval|QC",H8N:"LaSalle|QC",H8P:"LaSalle|QC",H8R:"Saint-Pierre|QC",H8S:"Lachine|QC",H8T:"Lachine|QC",H8Y:"Roxboro|QC",
  H8Z:"Pierrefonds|QC",H9A:"Dollard-Des-Ormeaux|QC",H9B:"Dollard-Des-Ormeaux|QC",H9C:"L'Île Bizard Northeast|QC",H9E:"L'Île-Bizard Southwest|QC",H9G:"Dollard-Des-Ormeaux|QC",H9H:"Sainte-Geneviève|QC",H9J:"Montréal|QC",H9K:"Senneville|QC",H9P:"Montréal|QC",
  H9R:"Montréal|QC",H9S:"L'Île-Dorval|QC",H9W:"Montréal|QC",H9X:"Sainte-Anne-De-Bellevue|QC",J0A:"Centre-du-Québec|QC",J0B:"Estrie|QC",J0C:"Centre-du-Québec|QC",J0E:"Fulford|QC",J0G:"Odanak|QC",J0H:"Saint-Nazaire-D'Acton|QC",
  J0J:"Montérégie|QC",J0K:"Lanaudière|QC",J0L:"Montérégie|QC",J0M:"Kuujjuaq|QC",J0N:"Oka|QC",J0P:"Coteau-du-Lac|QC",J0R:"Prévost|QC",J0S:"Montérégie|QC",J0T:"Laurentides|QC",J0V:"Chénéville|QC",
  J0W:"Ferme-Neuve|QC",J0X:"Outaouais|QC",J0Y:"Radisson|QC",J0Z:"Abitibi-Témiscamingue|QC",J1A:"Coaticook|QC",J1C:"Bromptonville|QC",J1E:"Sherbrooke|QC",J1G:"Sherbrooke|QC",J1H:"Sherbrooke|QC",J1J:"Sherbrooke|QC",
  J1K:"Sherbrooke|QC",J1L:"Sherbrooke|QC",J1M:"Sherbrooke|QC",J1N:"Rock Forest|QC",J1R:"Saint-Élie-d'Orford|QC",J1S:"Estrie|QC",J1T:"Estrie|QC",J1X:"Estrie|QC",J1Z:"Saint-Cyrille-De-Wendover|QC",J2A:"Centre-du-Québec|QC",
  J2B:"Drummondville South|QC",J2C:"Centre-du-Québec|QC",J2E:"Centre-du-Québec|QC",J2G:"Montérégie|QC",J2H:"Montérégie|QC",J2J:"Montérégie|QC",J2K:"Montérégie|QC",J2L:"Montérégie|QC",J2M:"Montérégie|QC",J2N:"Montérégie|QC",
  J2R:"Montérégie|QC",J2S:"Montérégie|QC",J2T:"Montérégie|QC",J2W:"Saint-Luc|QC",J2X:"Montérégie|QC",J2Y:"Montérégie|QC",J3A:"Montérégie|QC",J3B:"Montérégie|QC",J3E:"Montérégie|QC",J3G:"Montérégie|QC",
  J3H:"Beloeil East|QC",J3L:"Montérégie|QC",J3M:"Montérégie|QC",J3N:"Saint-Basile-Le-Grand|QC",J3P:"Sorel|QC",J3R:"Sorel|QC",J3T:"Centre-du-Québec|QC",J3V:"Saint-Bruno|QC",J3X:"Montérégie|QC",J3Y:"Saint-Hubert|QC",
  J3Z:"Saint-Hubert|QC",J4B:"Montérégie|QC",J4G:"Longueuil|QC",J4H:"Longueuil|QC",J4J:"Longueuil|QC",J4K:"Longueuil|QC",J4L:"Longueuil|QC",J4M:"Longueuil|QC",J4N:"Longueuil|QC",J4P:"Montérégie|QC",
  J4R:"Montérégie|QC",J4S:"Montérégie|QC",J4T:"Saint-Hubert West|QC",J4V:"Greenfield Park|QC",J4W:"Montérégie|QC",J4X:"Montérégie|QC",J4Y:"Montérégie|QC",J4Z:"Montérégie|QC",J5A:"Montérégie|QC",J5B:"Montérégie|QC",
  J5C:"Montérégie|QC",J5J:"Saint-Sophie|QC",J5K:"Laurentides|QC",J5L:"Laurentides|QC",J5M:"Lanaudière|QC",J5R:"Montérégie|QC",J5T:"Lanaudière|QC",J5V:"Mauricie|QC",J5W:"L'Assomption|QC",J5X:"Lanaudière|QC",
  J5Y:"Lanaudière|QC",J5Z:"Lanaudière|QC",J6A:"Lanaudière|QC",J6E:"Joliette|QC",J6J:"Montérégie|QC",J6K:"Montérégie|QC",J6N:"Montérégie|QC",J6R:"Montérégie|QC",J6S:"Montérégie|QC",J6T:"Montérégie|QC",
  J6V:"Lanaudière|QC",J6W:"Lanaudière|QC",J6X:"Lanaudière|QC",J6Y:"Lanaudière|QC",J6Z:"Sainte-Thérèse-de-Blainville Northeast|QC",J7A:"Sainte-Thérèse-de-Blainville|QC",J7B:"Sainte-Thérèse-de-Blainville|QC",J7C:"Sainte-Thérèse-de-Blainville|QC",J7E:"Laurentides|QC",J7G:"Sainte-Thérèse-de-Blainville|QC",
  J7H:"Sainte-Thérèse-de-Blainville|QC",J7J:"Mirabel|QC",J7K:"Lanaudière|QC",J7L:"Lanaudière|QC",J7M:"La Plaine|QC",J7N:"Mirabel|QC",J7P:"Laurentides|QC",J7R:"Laurentides|QC",J7T:"Vaudreuil-Dorion RCM|QC",J7V:"Montérégie|QC",
  J7W:"Pincourt|QC",J7X:"Valleyfield|QC",J7Y:"Laurentides|QC",J7Z:"Laurentides|QC",J8A:"Laurentides|QC",J8B:"Laurentides|QC",J8C:"Sainte-Agathe-Des-Monts|QC",J8E:"Laurentides|QC",J8G:"Chatham|QC",J8H:"Laurentides|QC",
  J8L:"Buckingham|QC",J8M:"Masson-Angers|QC",J8N:"Outaouais|QC",J8P:"Gatineau|QC",J8R:"Gatineau|QC",J8T:"Gatineau|QC",J8V:"Gatineau|QC",J8X:"Hull|QC",J8Y:"Hull|QC",J8Z:"Hull|QC",
  J9A:"Hull Southwest|QC",J9B:"Outaouais|QC",J9E:"Outaouais|QC",J9H:"Aylmer|QC",J9J:"Aylmer|QC",J9L:"Laurentides|QC",J9P:"Abitibi-Témiscamingue|QC",J9T:"Abitibi-Témiscamingue|QC",J9V:"Abitibi-Témiscamingue|QC",J9X:"Rouyn-Noranda|QC",
  J9Y:"Rouyn-Noranda|QC",J9Z:"Abitibi-Témiscamingue|QC",K0A:"Almonte|ON",K0B:"Alfred|ON",K0C:"Alexandria|ON",K0E:"Prescott|ON",K0G:"Kemptville|ON",K0H:"Frontenac County|ON",K0J:"Renfrew County|ON",K0K:"Picton|ON",
  K0L:"Peterborough County|ON",K0M:"Bobcaygeon|ON",K1A:"Ottawa|ON",K1B:"Gloucester|ON",K1C:"Gloucester|ON",K1E:"Queenswood|ON",K1G:"Ottawa|ON",K1H:"Ottawa|ON",K1J:"Gloucester|ON",K1K:"Ottawa|ON",
  K1L:"Ottawa|ON",K1M:"Ottawa|ON",K1N:"Ottawa|ON",K1P:"Ottawa|ON",K1R:"Ottawa|ON",K1S:"Ottawa|ON",K1T:"Gloucester|ON",K1V:"Ottawa|ON",K1W:"Gloucester|ON",K1X:"Gloucester|ON",
  K1Y:"Ottawa|ON",K1Z:"Ottawa|ON",K2A:"Ottawa|ON",K2B:"Ottawa|ON",K2C:"Ottawa|ON",K2E:"Nepean|ON",K2G:"Nepean|ON",K2H:"Nepean|ON",K2J:"Nepean|ON",K2K:"Kanata|ON",
  K2L:"Kanata|ON",K2M:"Kanata|ON",K2P:"Ottawa|ON",K2R:"Nepean|ON",K2S:"Stittsville|ON",K2T:"Kanata|ON",K2V:"Kanata|ON",K2W:"Kanata|ON",K4A:"Fallingbrook|ON",K4B:"Cumberland Township|ON",
  K4C:"Cumberland|ON",K4K:"Rockland|ON",K4M:"Manotick|ON",K4P:"Greely|ON",K4R:"Russell|ON",K6A:"Hawkesbury|ON",K6H:"Cornwall|ON",K6J:"Cornwall|ON",K6K:"Cornwall|ON",K6T:"Elizabethtown|ON",
  K6V:"Brockville|ON",K7A:"Smiths Falls|ON",K7C:"Carleton Place|ON",K7G:"Gananoque|ON",K7H:"Perth|ON",K7K:"Kingston|ON",K7L:"Kingston|ON",K7M:"Kingston|ON",K7N:"Amherstview|ON",K7P:"Kingston|ON",
  K7R:"Napanee|ON",K7S:"Arnprior|ON",K7V:"Renfrew|ON",K8A:"Pembroke|ON",K8B:"Pembroke|ON",K8H:"Petawawa|ON",K8N:"Belleville|ON",K8P:"Belleville|ON",K8R:"Belleville|ON",K8V:"Trenton|ON",
  K9A:"Cobourg|ON",K9H:"Peterborough|ON",K9J:"Peterborough|ON",K9K:"Peterborough|ON",K9L:"Peterborough|ON",K9V:"Lindsay|ON",L0A:"Millbrook|ON",L0B:"Orono|ON",L0C:"Sunderland|ON",L0E:"Lake Simcoe|ON",
  L0G:"Queensville|ON",L0H:"Gormley|ON",L0J:"Kleinburg|ON",L0K:"Lake Simcoe|ON",L0L:"Lake Simcoe|ON",L0M:"Angus|ON",L0N:"Dufferin County|ON",L0P:"Halton|ON",L0R:"Waterdown|ON",L0S:"Fonthill|ON",
  L1A:"Port Hope|ON",L1B:"Bowmanville|ON",L1C:"Bowmanville|ON",L1E:"Courtice|ON",L1G:"Oshawa|ON",L1H:"Oshawa|ON",L1J:"Oshawa|ON",L1K:"Oshawa|ON",L1L:"Oshawa|ON",L1M:"Whitby|ON",
  L1N:"Whitby|ON",L1P:"Whitby|ON",L1R:"Whitby|ON",L1S:"Ajax|ON",L1T:"Ajax|ON",L1V:"Pickering|ON",L1W:"Pickering|ON",L1X:"Pickering|ON",L1Y:"Pickering|ON",L1Z:"Ajax|ON",
  L2A:"Fort Erie|ON",L2E:"Niagara Falls|ON",L2G:"Niagara Falls|ON",L2H:"Niagara Falls|ON",L2J:"Niagara Falls|ON",L2M:"St. Catharines|ON",L2N:"St. Catharines|ON",L2P:"St. Catharines|ON",L2R:"St. Catharines|ON",L2S:"St. Catharines|ON",
  L2T:"St. Catharines|ON",L2V:"St. Catharines|ON",L2W:"St. Catharines|ON",L3B:"Welland|ON",L3C:"Welland|ON",L3K:"Port Colborne|ON",L3M:"Grimsby|ON",L3P:"Markham|ON",L3R:"Markham|ON",L3S:"Markham|ON",
  L3T:"Thornhill East|ON",L3V:"Orillia|ON",L3X:"Newmarket|ON",L3Y:"Newmarket|ON",L3Z:"Bradford|ON",L4A:"Stouffville|ON",L4B:"Richmond Hill|ON",L4C:"Richmond Hill|ON",L4E:"Richmond Hill|ON",L4G:"Aurora|ON",
  L4H:"Woodbridge|ON",L4J:"Thornhill West|ON",L4K:"Concord|ON",L4L:"Woodbridge|ON",L4M:"Barrie|ON",L4N:"Barrie|ON",L4P:"Keswick|ON",L4R:"Midland|ON",L4S:"Richmond Hill|ON",L4T:"Mississauga|ON",
  L4V:"Mississauga|ON",L4W:"Mississauga|ON",L4X:"Mississauga|ON",L4Y:"Mississauga|ON",L4Z:"Mississauga|ON",L5A:"Mississauga|ON",L5B:"Mississauga|ON",L5C:"Mississauga|ON",L5E:"Mississauga|ON",L5G:"Mississauga|ON",
  L5H:"Mississauga|ON",L5J:"Mississauga|ON",L5K:"Mississauga|ON",L5L:"Mississauga|ON",L5M:"Mississauga|ON",L5N:"Mississauga|ON",L5P:"Mississauga|ON",L5R:"Mississauga|ON",L5S:"Mississauga|ON",L5T:"Mississauga|ON",
  L5V:"Mississauga|ON",L5W:"Mississauga|ON",L6A:"Maple|ON",L6B:"Markham|ON",L6C:"Markham|ON",L6E:"Markham|ON",L6G:"Markham|ON",L6H:"Oakville|ON",L6J:"Oakville|ON",L6K:"Oakville|ON",
  L6L:"Oakville|ON",L6M:"Oakville|ON",L6P:"Brampton|ON",L6R:"Brampton|ON",L6S:"Brampton|ON",L6T:"Brampton|ON",L6V:"Brampton|ON",L6W:"Brampton|ON",L6X:"Brampton|ON",L6Y:"Brampton|ON",
  L6Z:"Brampton|ON",L7A:"Brampton West|ON",L7B:"King City|ON",L7C:"Caledon|ON",L7E:"Bolton|ON",L7G:"Georgetown|ON",L7J:"Acton|ON",L7K:"Caledon Village|ON",L7L:"Burlington|ON",L7M:"Burlington|ON",
  L7N:"Burlington|ON",L7P:"Burlington|ON",L7R:"Burlington|ON",L7S:"Burlington|ON",L7T:"Burlington|ON",L8B:"Waterdown|ON",L8E:"Hamilton|ON",L8G:"Hamilton|ON",L8H:"Hamilton|ON",L8J:"Hamilton|ON",
  L8K:"Hamilton|ON",L8L:"Hamilton|ON",L8M:"Hamilton|ON",L8N:"Hamilton|ON",L8P:"Hamilton|ON",L8R:"Hamilton|ON",L8S:"Hamilton|ON",L8T:"Hamilton|ON",L8V:"Hamilton|ON",L8W:"Hamilton|ON",
  L9A:"Hamilton|ON",L9B:"Hamilton|ON",L9C:"Hamilton|ON",L9E:"Halton|ON",L9G:"Ancaster|ON",L9H:"Dundas|ON",L9J:"Barrie|ON",L9K:"Ancaster|ON",L9L:"Port Perry|ON",L9M:"Penetanguishene|ON",
  L9N:"Holland Landing|ON",L9P:"Uxbridge|ON",L9R:"Alliston|ON",L9S:"Innisfil|ON",L9T:"Milton|ON",L9V:"Orangeville|ON",L9W:"Orangeville|ON",L9X:"Springwater|ON",L9Y:"Collingwood|ON",L9Z:"Wasaga Beach|ON",
  M1B:"Scarborough|ON",M1C:"Scarborough|ON",M1E:"Scarborough|ON",M1G:"Scarborough|ON",M1H:"Scarborough|ON",M1J:"Scarborough|ON",M1K:"Scarborough|ON",M1L:"Scarborough|ON",M1M:"Scarborough|ON",M1N:"Scarborough|ON",
  M1P:"Scarborough|ON",M1R:"Scarborough|ON",M1S:"Scarborough|ON",M1T:"Scarborough|ON",M1V:"Scarborough|ON",M1W:"Scarborough|ON",M1X:"Scarborough|ON",M2H:"North York|ON",M2J:"North York|ON",M2K:"North York|ON",
  M2L:"North York|ON",M2M:"Willowdale|ON",M2N:"Willowdale|ON",M2P:"North York|ON",M2R:"Willowdale|ON",M3A:"North York|ON",M3B:"Don Mills|ON",M3C:"Don Mills|ON",M3H:"North York|ON",M3J:"North York|ON",
  M3K:"Toronto|ON",M3L:"Downsview|ON",M3M:"Downsview|ON",M3N:"North York|ON",M4A:"North York|ON",M4B:"East York|ON",M4C:"East York|ON",M4E:"Toronto|ON",M4G:"East York|ON",M4H:"East York|ON",
  M4J:"Toronto|ON",M4K:"Toronto|ON",M4L:"Toronto|ON",M4M:"Toronto|ON",M4N:"Toronto|ON",M4P:"Toronto|ON",M4R:"Toronto|ON",M4S:"Toronto|ON",M4T:"Toronto|ON",M4V:"Toronto|ON",
  M4W:"Toronto|ON",M4X:"Toronto|ON",M4Y:"Toronto|ON",M5A:"Toronto|ON",M5B:"Toronto|ON",M5C:"Toronto|ON",M5E:"Toronto|ON",M5G:"Toronto|ON",M5H:"Toronto|ON",M5J:"Toronto|ON",
  M5K:"Toronto|ON",M5L:"Toronto|ON",M5M:"North York|ON",M5N:"Toronto|ON",M5P:"Toronto|ON",M5R:"Toronto|ON",M5S:"Toronto|ON",M5T:"Toronto|ON",M5V:"Toronto|ON",M5W:"Toronto|ON",
  M5X:"Toronto|ON",M6A:"North York|ON",M6B:"North York|ON",M6C:"York|ON",M6E:"York|ON",M6G:"Toronto|ON",M6H:"Toronto|ON",M6J:"Toronto|ON",M6K:"Toronto|ON",M6L:"North York|ON",
  M6M:"York|ON",M6N:"York|ON",M6P:"Toronto|ON",M6R:"Toronto|ON",M6S:"Toronto|ON",M7A:"Queen's Park Ontario Provincial Government|ON",M7Y:"Toronto|ON",M8V:"Toronto|ON",M8W:"Etobicoke|ON",M8X:"Etobicoke|ON",
  M8Y:"Etobicoke|ON",M8Z:"Etobicoke|ON",M9A:"Etobicoke|ON",M9B:"Etobicoke|ON",M9C:"Etobicoke|ON",M9L:"North York|ON",M9M:"North York|ON",M9N:"Weston|ON",M9P:"Etobicoke|ON",M9R:"Etobicoke|ON",
  M9V:"Etobicoke|ON",M9W:"Etobicoke|ON",N0A:"Port Dover|ON",N0B:"Elora|ON",N0C:"Dundalk|ON",N0E:"Waterford|ON",N0G:"Wingham|ON",N0H:"Wiarton|ON",N0J:"Norwich|ON",N0K:"Mitchell|ON",
  N0L:"Dorchester|ON",N0M:"Clinton|ON",N0N:"Forest|ON",N0P:"Blenheim|ON",N0R:"Belle River|ON",N1A:"Dunnville|ON",N1C:"Guelph|ON",N1E:"Guelph|ON",N1G:"Guelph|ON",N1H:"Guelph|ON",
  N1K:"Guelph|ON",N1L:"Guelph|ON",N1M:"Fergus|ON",N1P:"Cambridge|ON",N1R:"Cambridge|ON",N1S:"Cambridge|ON",N1T:"Cambridge|ON",N2A:"Kitchener|ON",N2B:"Kitchener|ON",N2C:"Kitchener|ON",
  N2E:"Kitchener|ON",N2G:"Kitchener|ON",N2H:"Kitchener|ON",N2J:"Waterloo|ON",N2K:"Kitchener|ON",N2L:"Waterloo|ON",N2M:"Kitchener|ON",N2N:"Kitchener|ON",N2P:"Kitchener|ON",N2R:"Kitchener|ON",
  N2T:"Waterloo|ON",N2V:"Waterloo|ON",N2Z:"Kincardine|ON",N3A:"Baden|ON",N3B:"Elmira|ON",N3C:"Cambridge|ON",N3E:"Cambridge|ON",N3H:"Cambridge|ON",N3L:"Paris|ON",N3P:"Brant|ON",
  N3R:"Brant|ON",N3S:"Brant|ON",N3T:"Brant|ON",N3V:"Brant|ON",N3W:"Caledonia|ON",N3Y:"Simcoe|ON",N4B:"Delhi|ON",N4G:"Tillsonburg|ON",N4K:"Owen Sound|ON",N4L:"Meaford|ON",
  N4N:"Hanover|ON",N4S:"Woodstock|ON",N4T:"Woodstock|ON",N4V:"Woodstock|ON",N4W:"Listowel|ON",N4X:"St. Mary's|ON",N4Z:"Stratford South|ON",N5A:"Stratford North|ON",N5C:"Ingersoll|ON",N5H:"Aylmer|ON",
  N5L:"Port Stanley|ON",N5P:"St. Thomas|ON",N5R:"St. Thomas|ON",N5V:"London|ON",N5W:"London|ON",N5X:"London|ON",N5Y:"London|ON",N5Z:"London|ON",N6A:"London|ON",N6B:"London|ON",
  N6C:"London|ON",N6E:"London|ON",N6G:"London|ON",N6H:"London|ON",N6J:"London|ON",N6K:"London|ON",N6L:"London|ON",N6M:"London|ON",N6N:"London|ON",N6P:"London|ON",
  N7A:"Goderich|ON",N7G:"Strathroy|ON",N7L:"Chatham|ON",N7M:"Chatham|ON",N7S:"Sarnia|ON",N7T:"Sarnia|ON",N7V:"Sarnia|ON",N7W:"Sarnia|ON",N7X:"Sarnia|ON",N8A:"Wallaceburg|ON",
  N8H:"Leamington|ON",N8M:"Essex|ON",N8N:"Tecumseh|ON",N8P:"Windsor|ON",N8R:"Windsor|ON",N8S:"Windsor|ON",N8T:"Windsor|ON",N8V:"Tecumseh|ON",N8W:"Windsor|ON",N8X:"Windsor|ON",
  N8Y:"Windsor|ON",N9A:"Windsor|ON",N9B:"Windsor|ON",N9C:"Windsor|ON",N9E:"Windsor|ON",N9G:"Windsor|ON",N9H:"La Salle|ON",N9J:"La Salle|ON",N9K:"Tecumseh Central|ON",N9V:"Amherstburg|ON",
  N9Y:"Kingsville|ON",P0A:"Nipissing|ON",P0B:"Nipissing|ON",P0C:"Parry Sound|ON",P0E:"Parry Sound|ON",P0G:"Parry Sound|ON",P0H:"Nipissing|ON",P0J:"Timiskaming|ON",P0K:"Timiskaming|ON",P0L:"Hearst|ON",
  P0M:"Chelmsford|ON",P0N:"South Porcupine|ON",P0P:"Little Current|ON",P0R:"Algoma|ON",P0S:"Lake Superior|ON",P0T:"Lake Superior|ON",P0V:"Red Lake|ON",P0W:"Emo|ON",P0X:"Keewatin|ON",P0Y:"Ingolf|ON",
  P1A:"North Bay|ON",P1B:"North Bay|ON",P1C:"North Bay|ON",P1H:"Huntsville|ON",P1L:"Bracebridge|ON",P1P:"Gravenhurst|ON",P2A:"Parry Sound|ON",P2B:"Sturgeon Falls|ON",P2N:"Kirkland Lake|ON",P3A:"Greater Sudbury|ON",
  P3B:"Greater Sudbury|ON",P3C:"Greater Sudbury|ON",P3E:"Greater Sudbury|ON",P3G:"Greater Sudbury|ON",P3L:"Greater Sudbury|ON",P3N:"Greater Sudbury|ON",P3P:"Greater Sudbury|ON",P3Y:"Greater Sudbury|ON",P4N:"Timmins|ON",P4P:"Timmins|ON",
  P4R:"Timmins|ON",P5A:"Elliot Lake|ON",P5E:"Espanola|ON",P5N:"Kapuskasing|ON",P6A:"Sault Ste.|ON",P6B:"Sault Ste.|ON",P6C:"Sault Ste.|ON",P7A:"Thunder Bay|ON",P7B:"Thunder Bay|ON",P7C:"Thunder Bay|ON",
  P7E:"Thunder Bay|ON",P7G:"Thunder Bay|ON",P7J:"Thunder Bay|ON",P7K:"Thunder Bay|ON",P7L:"Neebing|ON",P8N:"Dryden|ON",P8T:"Sioux Lookout|ON",P9A:"Fort Frances|ON",P9N:"Kenora|ON",R0A:"Lorette|MB",
  R0B:"Norway House|MB",R0C:"Stonewall|MB",R0E:"Beausejour|MB",R0G:"South|MB",R0H:"South|MB",R0J:"Neepawa|MB",R0K:"Killarney|MB",R0L:"Swan River|MB",R0M:"Virden|MB",R1A:"Selkirk|MB",
  R1B:"Lockport|MB",R1C:"Narol|MB",R1N:"Portage la Prairie|MB",R2C:"Winnipeg|MB",R2E:"East St. Paul|MB",R2G:"Winnipeg|MB",R2H:"Winnipeg|MB",R2J:"Winnipeg|MB",R2K:"Winnipeg|MB",R2L:"Winnipeg|MB",
  R2M:"Winnipeg|MB",R2N:"Winnipeg|MB",R2P:"Winnipeg|MB",R2R:"Winnipeg|MB",R2V:"Winnipeg|MB",R2W:"Winnipeg|MB",R2X:"Winnipeg|MB",R2Y:"Winnipeg|MB",R3A:"Winnipeg|MB",R3B:"Winnipeg|MB",
  R3C:"Winnipeg|MB",R3E:"Winnipeg|MB",R3G:"Winnipeg|MB",R3H:"Winnipeg|MB",R3J:"Winnipeg|MB",R3K:"Winnipeg|MB",R3L:"Winnipeg|MB",R3M:"Winnipeg|MB",R3N:"Winnipeg|MB",R3P:"Winnipeg|MB",
  R3R:"Winnipeg|MB",R3S:"Winnipeg|MB",R3T:"Winnipeg|MB",R3V:"Winnipeg|MB",R3W:"Winnipeg|MB",R3X:"Winnipeg|MB",R3Y:"Winnipeg|MB",R4A:"West St. Paul|MB",R4G:"Oak Bluff|MB",R4H:"Headingley|MB",
  R4J:"Headingley|MB",R4K:"Cartier|MB",R4L:"St. Francois Xavier|MB",R5A:"St. Adolphe|MB",R5G:"Steinbach|MB",R5H:"Ste. Anne|MB",R5K:"Taché|MB",R6M:"Morden|MB",R6W:"Winkler|MB",R7A:"Brandon|MB",
  R7B:"Brandon|MB",R7C:"Brandon|MB",R7N:"Dauphin|MB",R8A:"Flin Flon|MB",R8N:"Thompson|MB",R9A:"The Pas|MB",S0A:"Melville|SK",S0C:"Carlyle|SK",S0E:"Melfort|SK",S0G:"Fort Qu'Appelle|SK",
  S0H:"Assiniboia|SK",S0J:"La Ronge|SK",S0K:"Humboldt|SK",S0L:"Kindersley|SK",S0M:"Battleford|SK",S0N:"Maple Creek|SK",S0P:"Creighton|SK",S2V:"Buena Vista|SK",S3N:"Yorkton|SK",S4A:"Estevan|SK",
  S4H:"Weyburn|SK",S4K:"Rm Of Sherwood|SK",S4L:"Regina|SK",S4M:"Regina|SK",S4N:"Regina|SK",S4P:"Regina|SK",S4R:"Regina|SK",S4S:"Regina|SK",S4T:"Regina|SK",S4V:"Regina|SK",
  S4W:"Regina|SK",S4X:"Regina|SK",S4Y:"Regina|SK",S4Z:"Regina|SK",S6H:"Moose Jaw|SK",S6J:"Moose Jaw|SK",S6K:"Moose Jaw|SK",S6V:"Prince Albert|SK",S6W:"Prince Albert|SK",S6X:"Prince Albert|SK",
  S7H:"Saskatoon|SK",S7J:"Saskatoon|SK",S7K:"Saskatoon|SK",S7L:"Saskatoon|SK",S7M:"Saskatoon|SK",S7N:"Saskatoon|SK",S7P:"Saskatoon|SK",S7R:"Saskatoon|SK",S7S:"Saskatoon|SK",S7T:"Saskatoon|SK",
  S7V:"Saskatoon|SK",S7W:"Saskatoon|SK",S9A:"North Battleford|SK",S9H:"Swift Current|SK",S9V:"Lloydminster|SK",S9X:"Meadow Lake|SK",T0A:"St. Paul|AB",T0B:"Tofield|AB",T0C:"Stettler|AB",T0E:"Jasper|AB",
  T0G:"Slave Lake|AB",T0H:"High Level|AB",T0J:"Drumheller|AB",T0K:"Cardston|AB",T0L:"Claresholm|AB",T0M:"Sundre|AB",T0P:"Fort Chipewyan|AB",T0V:"Fitzgerald|AB",T1A:"Medicine Hat|AB",T1B:"Medicine Hat|AB",
  T1C:"Medicine Hat|AB",T1G:"Taber|AB",T1H:"Lethbridge|AB",T1J:"Lethbridge|AB",T1K:"Lethbridge|AB",T1L:"Banff|AB",T1M:"Coaldale|AB",T1P:"Strathmore|AB",T1R:"Brooks|AB",T1S:"Okotoks|AB",
  T1V:"High River|AB",T1W:"Canmore|AB",T1X:"Chestermere|AB",T1Y:"Calgary|AB",T1Z:"Rocky View|AB",T2A:"Calgary|AB",T2B:"Calgary|AB",T2C:"Calgary|AB",T2E:"Calgary|AB",T2G:"Calgary|AB",
  T2H:"Calgary|AB",T2J:"Calgary|AB",T2K:"Calgary|AB",T2L:"Calgary|AB",T2M:"Calgary|AB",T2N:"Calgary|AB",T2P:"Calgary|AB",T2R:"Calgary|AB",T2S:"Calgary|AB",T2T:"Calgary|AB",
  T2V:"Calgary|AB",T2W:"Calgary|AB",T2X:"Calgary|AB",T2Y:"Calgary|AB",T2Z:"Calgary|AB",T3A:"Calgary|AB",T3B:"Calgary|AB",T3C:"Calgary|AB",T3E:"Calgary|AB",T3G:"Calgary|AB",
  T3H:"Calgary|AB",T3J:"Calgary|AB",T3K:"Calgary|AB",T3L:"Calgary|AB",T3M:"Calgary|AB",T3N:"Calgary|AB",T3P:"Calgary|AB",T3R:"Calgary|AB",T3S:"Calgary|AB",T3T:"Tsuut'ina|AB",
  T3Z:"Redwood Meadows|AB",T4A:"Airdrie|AB",T4B:"Airdrie|AB",T4C:"Cochrane|AB",T4E:"Red Deer|AB",T4G:"Innisfail|AB",T4H:"Olds|AB",T4J:"Ponoka|AB",T4L:"Lacombe|AB",T4M:"Blackfalds|AB",
  T4N:"Red Deer|AB",T4P:"Red Deer|AB",T4R:"Red Deer|AB",T4S:"Sylvan Lake|AB",T4T:"Rocky Mountain House|AB",T4V:"Camrose|AB",T4X:"Beaumont|AB",T5A:"Edmonton|AB",T5B:"Edmonton|AB",T5C:"Edmonton|AB",
  T5E:"Edmonton|AB",T5G:"Edmonton|AB",T5H:"Edmonton|AB",T5J:"Edmonton|AB",T5K:"Edmonton|AB",T5L:"Edmonton|AB",T5M:"Edmonton|AB",T5N:"Edmonton|AB",T5P:"Edmonton|AB",T5R:"Edmonton|AB",
  T5S:"Edmonton|AB",T5T:"Edmonton|AB",T5V:"Edmonton|AB",T5W:"Edmonton|AB",T5X:"Edmonton|AB",T5Y:"Edmonton|AB",T5Z:"Edmonton|AB",T6A:"Edmonton|AB",T6B:"Edmonton|AB",T6C:"Edmonton|AB",
  T6E:"Edmonton|AB",T6G:"Edmonton|AB",T6H:"Edmonton|AB",T6J:"Edmonton|AB",T6K:"Edmonton|AB",T6L:"Edmonton|AB",T6M:"Edmonton|AB",T6N:"Edmonton|AB",T6P:"Edmonton|AB",T6R:"Edmonton|AB",
  T6S:"Edmonton|AB",T6T:"Edmonton|AB",T6V:"Edmonton|AB",T6W:"Edmonton|AB",T6X:"Edmonton|AB",T7A:"Drayton Valley|AB",T7E:"Edson|AB",T7N:"Barrhead|AB",T7P:"Westlock|AB",T7S:"Whitecourt|AB",
  T7V:"Hinton|AB",T7X:"Spruce Grove|AB",T7Y:"Spruce Grove|AB",T7Z:"Stony Plain|AB",T8A:"Sherwood Park|AB",T8B:"Sherwood Park|AB",T8C:"Sherwood Park|AB",T8E:"Sherwood Park|AB",T8G:"Sherwood Park|AB",T8H:"Sherwood Park|AB",
  T8L:"Fort Saskatchewan|AB",T8N:"St. Albert|AB",T8R:"Morinville|AB",T8S:"Peace River|AB",T8T:"St. Albert|AB",T8V:"Grande Prairie|AB",T8W:"Grande Prairie|AB",T8X:"Grande Prairie|AB",T9A:"Wetaskiwin|AB",T9C:"Vegreville|AB",
  T9E:"Leduc|AB",T9G:"Devon|AB",T9H:"Fort McMurray|AB",T9J:"Fort McMurray|AB",T9K:"Fort McMurray|AB",T9M:"Cold Lake|AB",T9N:"Bonnyville|AB",T9S:"Athabasca|AB",T9V:"Lloydminster|AB",T9W:"Wainwright|AB",
  T9X:"Vermilion|AB",V0A:"Golden|BC",V0B:"Fernie|BC",V0C:"Fort Nelson|BC",V0E:"Revelstoke|BC",V0G:"Rossland|BC",V0H:"Summerland|BC",V0J:"Smithers|BC",V0K:"100 Mile House|BC",V0L:"Alexis Creek|BC",
  V0M:"Agassiz|BC",V0N:"Whistler|BC",V0P:"Gold River|BC",V0R:"Chemainus|BC",V0S:"Sooke|BC",V0T:"Queen Charlotte City|BC",V0V:"Port Edward|BC",V0W:"Atlin|BC",V0X:"Hope|BC",V1A:"Kimberley|BC",
  V1B:"Vernon|BC",V1C:"Cranbrook|BC",V1E:"Salmon Arm|BC",V1G:"Dawson Creek|BC",V1H:"Vernon|BC",V1J:"Fort St. John|BC",V1K:"Merritt|BC",V1L:"Nelson|BC",V1M:"Langley Township North|BC",V1N:"Castlegar|BC",
  V1P:"Kelowna|BC",V1R:"Trail|BC",V1S:"Kamloops Southwest|BC",V1T:"Vernon|BC",V1V:"Kelowna|BC",V1W:"Kelowna|BC",V1X:"Kelowna|BC",V1Y:"Kelowna|BC",V1Z:"Kelowna|BC",V2A:"Penticton|BC",
  V2B:"Kamloops|BC",V2C:"Kamloops|BC",V2E:"Kamloops|BC",V2G:"Williams Lake|BC",V2H:"Kamloops|BC",V2J:"Quesnel|BC",V2K:"Prince George|BC",V2L:"Prince George|BC",V2M:"Prince George|BC",V2N:"Prince George|BC",
  V2P:"Chilliwack|BC",V2R:"Chilliwack|BC",V2S:"Abbotsford|BC",V2T:"Abbotsford|BC",V2V:"Mission East|BC",V2W:"Maple Ridge|BC",V2X:"Maple Ridge|BC",V2Y:"Langley Township|BC",V2Z:"Langley Township|BC",V3A:"Langley City|BC",
  V3B:"Port Coquitlam|BC",V3C:"Port Coquitlam|BC",V3E:"Port Coquitlam|BC",V3G:"Abbotsford East|BC",V3H:"Port Moody|BC",V3J:"Coquitlam|BC",V3K:"Coquitlam|BC",V3L:"New Westminster|BC",V3M:"New Westminster|BC",V3N:"Burnaby|BC",
  V3R:"Surrey|BC",V3S:"Surrey|BC",V3T:"Surrey|BC",V3V:"Surrey|BC",V3W:"Surrey|BC",V3X:"Surrey|BC",V3Y:"Pitt Meadows|BC",V3Z:"Surrey|BC",V4A:"Surrey|BC",V4B:"White Rock|BC",
  V4C:"Delta|BC",V4E:"Delta|BC",V4G:"Delta|BC",V4K:"Delta|BC",V4L:"Delta|BC",V4M:"Delta|BC",V4N:"Surrey|BC",V4P:"Surrey|BC",V4R:"Maple Ridge Northwest|BC",V4S:"Mission West|BC",
  V4T:"Westbank|BC",V4V:"Winfield|BC",V4W:"Langley Township East|BC",V4X:"Abbotsford West|BC",V4Z:"Chilliwack East|BC",V5A:"Burnaby|BC",V5B:"Burnaby|BC",V5C:"Burnaby|BC",V5E:"Burnaby|BC",V5G:"Burnaby|BC",
  V5H:"Burnaby|BC",V5J:"Burnaby|BC",V5K:"Vancouver|BC",V5L:"Vancouver|BC",V5M:"Vancouver|BC",V5N:"Vancouver|BC",V5P:"Vancouver|BC",V5R:"Vancouver|BC",V5S:"Vancouver|BC",V5T:"Vancouver|BC",
  V5V:"Vancouver|BC",V5W:"Vancouver|BC",V5X:"Vancouver|BC",V5Y:"Vancouver|BC",V5Z:"Vancouver|BC",V6A:"Vancouver|BC",V6B:"Vancouver|BC",V6C:"Vancouver|BC",V6E:"Vancouver|BC",V6G:"Vancouver|BC",
  V6H:"Vancouver|BC",V6J:"Vancouver|BC",V6K:"Vancouver|BC",V6L:"Vancouver|BC",V6M:"Vancouver|BC",V6N:"Vancouver|BC",V6P:"Vancouver|BC",V6R:"Vancouver|BC",V6S:"Vancouver|BC",V6T:"Vancouver|BC",
  V6V:"Richmond|BC",V6W:"Richmond|BC",V6X:"Richmond|BC",V6Y:"Richmond|BC",V6Z:"Vancouver|BC",V7A:"Richmond|BC",V7B:"Richmond|BC",V7C:"Richmond|BC",V7E:"Richmond|BC",V7G:"Vancouver|BC",
  V7H:"Vancouver|BC",V7J:"Vancouver|BC",V7K:"Vancouver|BC",V7L:"Vancouver|BC",V7M:"Vancouver|BC",V7N:"Vancouver|BC",V7P:"Vancouver|BC",V7R:"Vancouver|BC",V7S:"Vancouver|BC",V7T:"Vancouver|BC",
  V7V:"Vancouver|BC",V7W:"Vancouver|BC",V7X:"Vancouver|BC",V7Y:"Vancouver|BC",V8A:"Powell River|BC",V8B:"Squamish|BC",V8C:"Kitimat|BC",V8E:"Whistler|BC",V8G:"Terrace|BC",V8J:"Prince Rupert|BC",
  V8K:"Saltspring Island|BC",V8L:"Sidney|BC",V8M:"Central Saanich|BC",V8N:"Saanich|BC",V8P:"Saanich|BC",V8R:"Oak Bay|BC",V8S:"Oak Bay|BC",V8T:"Victoria|BC",V8V:"Victoria|BC",V8W:"Victoria|BC",
  V8X:"Saanich|BC",V8Y:"Saanich|BC",V8Z:"Saanich|BC",V9A:"Esquimalt|BC",V9B:"Highlands|BC",V9C:"Metchosin|BC",V9E:"Saanich West|BC",V9G:"Ladysmith|BC",V9H:"Campbell River|BC",V9J:"Courtenay|BC",
  V9K:"Qualicum Beach|BC",V9L:"Duncan|BC",V9M:"Comox|BC",V9N:"Courtenay|BC",V9P:"Parksville|BC",V9R:"Nanaimo|BC",V9S:"Nanaimo|BC",V9T:"Nanaimo|BC",V9V:"Nanaimo|BC",V9W:"Campbell River|BC",
  V9X:"Cedar|BC",V9Y:"Port Alberni|BC",V9Z:"Sooke|BC",X0A:"Iqaluit|NU",X0B:"Cambridge Bay|NU",X0C:"Rankin Inlet|NU",X0E:"Inuvik|NT",X0G:"Fort Liard|NT",X1A:"Yellowknife|NT",Y0A:"Watson Lake|YT",
  Y0B:"Dawson City|YT",Y1A:"Whitehorse|YT",
};

/** Is this a forward sortation area anybody lives in? */
const has = (fsa) => Object.prototype.hasOwnProperty.call(
  FSA, String(fsa == null ? '' : fsa).toUpperCase()
);

/** -> { fsa, city, province } or null. Never throws on an unknown FSA. */
function lookup(fsa) {
  const key = String(fsa == null ? '' : fsa).toUpperCase();
  const packed = Object.prototype.hasOwnProperty.call(FSA, key) ? FSA[key] : null;
  if (!packed) return null;
  const cut = packed.lastIndexOf('|');
  return { fsa: key, city: packed.slice(0, cut), province: packed.slice(cut + 1) };
}

/** Every FSA the reference knows, sorted. For the admin console's picker. */
const all = () => Object.keys(FSA);

const META = Object.freeze({
  source: "GeoNames.org CA.txt (http://download.geonames.org/export/zip/CA.zip)",
  license: "CC BY 4.0 -- https://creativecommons.org/licenses/by/4.0/",
  builtOn: "2026-08-07",
  count: 1652,
});

module.exports = { has, lookup, all, META, COUNT: 1652 };
