'use strict';

/**
 * GENERATED by scripts/build-mixmath.mjs from partner/core/mixmath.js. Do NOT edit by hand.
 * Run the generator and commit the result, or the --check gate reports STALE.
 *
 * The custom mix arithmetic, server side: the same cents the console showed
 * the partner, sealed by the same function. lib/bids.js readBid() validates a
 * mix through checkMix() and seals tierSnapshot() per tier; nothing
 * downstream re-derives a cent.
 */

var MIX_MAX_ROWS = 5;

/* The reduction reads offered on the ticket minus 'none', which is the absence
   of a breakdown and cannot be a line in one, plus a row the partner words
   themselves. */
var MIX_TYPES = ['member', 'promo', 'cash', 'own'];

var MIX_TYPE_LABEL = {
  member: 'Whollar member discount',
  promo: 'Promotional credit',
  cash: 'Monthly cashback',
  own: 'Other, your wording'
};

/* The name households see on the line item. 'own' takes the partner's label. */
var MIX_TYPE_SHORT = {
  member: 'Member discount',
  promo: 'Promotional credit',
  cash: 'Monthly cashback',
  own: ''
};

/* A line-item label is free text echoed to households, so it is validated
   rather than merely stored: display charset only, and none of the pressure
   or condition language the standard cohort terms forbid. The server applies
   the same two rules to the derived mechanism label. */
var LABEL_RE = /^[A-Za-z0-9][A-Za-z0-9 ,.'&-]{2,39}$/;
var LABEL_BANNED = /today only|limited time|expires|last chance|hurry|act now|bundle|autopay|auto[- ]pay/i;

/** A canonical money string ("56.00", "86") or number, as integer cents. Null when it is not money. */
function toCents(v) {
  if (v === null || v === undefined || v === '') return null;
  var n = Number(String(v).replace(/[$,\s]/g, ''));
  if (!isFinite(n)) return null;
  return Math.round(n * 100);
}

/** Integer cents as a two-decimal string, "25.00". */
function centsStr(c) {
  var n = Math.round(Number(c) || 0);
  var neg = n < 0;
  n = Math.abs(n);
  var whole = Math.floor(n / 100);
  var frac = n % 100;
  return (neg ? '-' : '') + String(whole) + '.' + (frac < 10 ? '0' : '') + String(frac);
}

/**
 * A typed share as integer tenths of a percent, or null when it is not one.
 *
 * One decimal place at most, 0 to 100 inclusive. A comma is read as the
 * decimal mark too, so a partner on a fr-CA keyboard is not told 33,3 is not
 * a number. Anything else (a second decimal, a sign, letters, empty) is null,
 * and the caller decides what to say about it.
 */
function shareTenths(v) {
  if (v === null || v === undefined) return null;
  var s = String(v).trim().replace(',', '.');
  if (!/^[0-9]{1,3}(\.[0-9])?$/.test(s)) return null;
  var t = Math.round(Number(s) * 10);
  if (t < 0 || t > 1000) return null;
  return t;
}

/** Tenths as the figure a partner reads: 333 -> "33.3", 500 -> "50". */
function fmtShare(t) {
  var n = Math.round(Number(t) || 0);
  var whole = Math.floor(Math.abs(n) / 10);
  var tenth = Math.abs(n) % 10;
  return (n < 0 ? '-' : '') + String(whole) + (tenth ? '.' + String(tenth) : '');
}

/** The line-item name a row carries: the partner's wording on 'own', the type's short name otherwise. */
function rowLabel(r) {
  if (!r) return '';
  if (r.type === 'own') return String(r.label || '').trim();
  return MIX_TYPE_SHORT[r.type] || '';
}

/**
 * Split `gapCents` across rows by their shares, in whole cents, exactly.
 *
 * Largest remainder: each row takes the floor of its share, then the cents
 * that flooring left over go one at a time to the rows with the largest
 * fractional remainder, ties broken by row order. When the shares total 100%
 * the amounts total the gap, every time, whatever the gap. When they do not,
 * the floors are returned as they are: the live panel still shows a partner
 * what each row comes to while the sum is being corrected, and nothing seals
 * until it is.
 */
function allocate(gapCents, tenthsList) {
  var gap = Math.max(0, Math.round(Number(gapCents) || 0));
  var list = tenthsList || [];
  var n = list.length;
  var floors = [];
  var rems = [];
  var total = 0;
  var placed = 0;
  var i;
  for (i = 0; i < n; i++) {
    var t = Math.max(0, Math.round(Number(list[i]) || 0));
    var raw = gap * t;
    floors[i] = Math.floor(raw / 1000);
    rems[i] = raw % 1000;
    total += t;
    placed += floors[i];
  }
  if (total !== 1000 || n === 0) return floors;
  var order = [];
  for (i = 0; i < n; i++) order.push(i);
  order.sort(function (a, b) { return rems[b] - rems[a] || a - b; });
  var left = gap - placed;
  for (i = 0; i < left; i++) floors[order[i % n]] += 1;
  return floors;
}

/**
 * Whether these rows are a mix that can seal, and what to say if not.
 *
 *   rows      [{ type, label, sharePct }], sharePct as typed
 *   returns   { ok, sumTenths, rows: [{ tenths, problem }], problems, warnings }
 *
 * Problems block the seal; warnings do not. A single row carries the whole
 * reduction whatever its share input says, because the console locks that
 * input at 100 and the server should not refuse what the console could not
 * type. The copy is here, not in the views, so the console and the server's
 * 400 say the same sentence.
 */
function checkMix(rows) {
  var out = { ok: true, sumTenths: 0, rows: [], problems: [], warnings: [] };
  var list = rows || [];
  if (!list.length) {
    out.ok = false;
    out.problems.push('Give the mix at least one discount.');
    return out;
  }
  if (list.length > MIX_MAX_ROWS) {
    out.ok = false;
    out.problems.push('A mix carries at most ' + MIX_MAX_ROWS + ' discounts.');
  }
  var single = list.length === 1;
  var seen = {};
  var dup = false;
  var rowProblems = [];
  list.forEach(function (r) {
    var row = r || {};
    var t = single ? 1000 : shareTenths(row.sharePct);
    var problem = null;
    if (t === null) {
      problem = String(row.sharePct === undefined || row.sharePct === null ? '' : row.sharePct).trim() === ''
        ? 'Every row needs a share above zero, or remove the row.'
        : 'Enter each share as a number from 0.1 to 100, with one decimal at most.';
    } else if (t === 0) {
      problem = 'Every row needs a share above zero, or remove the row.';
    }
    if (MIX_TYPES.indexOf(row.type) < 0) {
      problem = problem || 'Pick a discount type on every row.';
    }
    var name = rowLabel(row);
    if (row.type === 'own') {
      if (!name) problem = problem || 'Give this discount a name households will see.';
      else if (!LABEL_RE.test(name)) problem = problem || 'Name this discount in 3 to 40 plain characters.';
      else if (LABEL_BANNED.test(name)) problem = problem || 'That name reads as pressure or a condition. The standard terms keep reductions unconditional.';
    }
    var key = name.toLowerCase();
    if (key) {
      if (seen[key]) dup = true;
      seen[key] = true;
    }
    out.rows.push({ tenths: t === null ? 0 : t, problem: problem });
    out.sumTenths += t === null ? 0 : t;
    if (problem && rowProblems.indexOf(problem) < 0) rowProblems.push(problem);
  });
  if (!single && out.sumTenths !== 1000) {
    out.ok = false;
    out.problems.push(out.sumTenths < 1000
      ? 'Your mix covers ' + fmtShare(out.sumTenths) + '% of the reduction. Add ' + fmtShare(1000 - out.sumTenths) + '% more.'
      : 'Your mix adds to ' + fmtShare(out.sumTenths) + '% of the reduction. Remove ' + fmtShare(out.sumTenths - 1000) + '%.');
  }
  if (rowProblems.length) {
    out.ok = false;
    rowProblems.forEach(function (p) { out.problems.push(p); });
  }
  if (dup) out.warnings.push('Two rows share the same name; households will see them as separate line items.');
  return out;
}

/**
 * The sealed snapshot for one tier: the prices in cents, the gap, and each
 * row's cents. This is the record households read, so the money is stored
 * and never re-derived downstream.
 *
 *   tier   { name, stickerPrice, effectivePrice }
 *   rows   [{ type, label, sharePct }], already through checkMix
 *   guar   guarantee months; every row runs the whole guarantee
 *
 * A tier whose sticker equals its effective has nothing to name: gapCents is
 * 0 and the mix is empty, which is a state and not an error. A negative gap is
 * a Price by service error upstream and is reported as gapCents < 0 with an
 * empty mix, so a caller can disable the editor for that tier.
 */
function tierSnapshot(tier, rows, guar) {
  var t = tier || {};
  var sticker = toCents(t.stickerPrice) || 0;
  var effective = toCents(t.effectivePrice) || 0;
  var gap = sticker - effective;
  var months = Number(guar) || 24;
  var snap = { tier: t.name || '', stickerCents: sticker, effectiveCents: effective, gapCents: gap, mix: [] };
  if (gap <= 0) return snap;
  var list = rows || [];
  var single = list.length === 1;
  var tenths = list.map(function (r) {
    var v = single ? 1000 : shareTenths((r || {}).sharePct);
    return v === null ? 0 : v;
  });
  var amounts = allocate(gap, tenths);
  snap.mix = list.map(function (r, i) {
    var row = r || {};
    return {
      type: row.type,
      label: rowLabel(row),
      sharePct: fmtShare(tenths[i]),
      amountCents: amounts[i],
      periodStartMo: 0,
      periodEndMo: months
    };
  });
  return snap;
}

module.exports = {
  MIX_MAX_ROWS, MIX_TYPES, MIX_TYPE_LABEL, MIX_TYPE_SHORT, LABEL_RE, LABEL_BANNED, toCents, centsStr, shareTenths, fmtShare, rowLabel, allocate, checkMix, tierSnapshot
};
