'use strict';

/**
 * GENERATED by scripts/build-places.mjs from partner/core/places.js. Do NOT edit by hand.
 * Run the generator and commit the result, or the --check gate reports STALE.
 *
 * The declarable coverage vocabulary, server side. 252 regions across
 * 157 cities, 6 of them launched.
 *
 * WHAT IT IS FOR. The region name is the whole join between a cohort and a
 * partner: requireActiveCoverage() in routes/desk.js compares
 * slug(coverage.region) to slug(campaign.region) exactly. A campaign created
 * with a name outside this list is a campaign no partner can ever bid on, and
 * nothing about it looks broken until the auction closes with no bids. The
 * picker constrains one side of that in the browser; this file is what lets the
 * write path constrain the other side, where it counts.
 *
 * LAUNCH IS NOT DECORATION. The picker offers only launch-city regions as
 * selectable, so a cohort in a queued city cannot be declared against by
 * anyone. Campaign creation therefore requires a launch region; declaring
 * coverage requires only a known one, because a partner may register interest
 * in a queued city and an operator leaves that row 'soon'.
 */

const PLACES = [
  { city: "Brampton", province: "Ontario", launch: true,
    regions: ["Brampton Central","Brampton East","Brampton West"] },
  { city: "Markham", province: "Ontario", launch: true,
    regions: ["Markham Centre","Markham North","Markham South"] },
  { city: "Mississauga", province: "Ontario", launch: true,
    regions: ["Mississauga City Centre","Mississauga Lakeshore","Mississauga West","Mississauga East","Mississauga North"] },
  { city: "Richmond Hill", province: "Ontario", launch: true,
    regions: ["Richmond Hill South","Richmond Hill North"] },
  { city: "Toronto", province: "Ontario", launch: true,
    regions: ["Scarborough Southwest","Scarborough Centre","Scarborough East","Scarborough North","North York West","North York Central","North York East","North York South","Etobicoke Lakeshore","Etobicoke Centre","Etobicoke North","East York","York","Downtown Core","Downtown East","Downtown West","Midtown","The Annex","West End","East End"] },
  { city: "Vaughan", province: "Ontario", launch: true,
    regions: ["Vaughan Woodbridge","Maple and VMC","Thornhill Vaughan","Kleinburg"] },
  { city: "Ajax", province: "Ontario", launch: false,
    regions: ["Ajax"] },
  { city: "Arnprior", province: "Ontario", launch: false,
    regions: ["Arnprior"] },
  { city: "Aurora", province: "Ontario", launch: false,
    regions: ["Aurora"] },
  { city: "Barrie", province: "Ontario", launch: false,
    regions: ["Barrie"] },
  { city: "Belleville", province: "Ontario", launch: false,
    regions: ["Belleville"] },
  { city: "Bracebridge", province: "Ontario", launch: false,
    regions: ["Bracebridge"] },
  { city: "Bradford", province: "Ontario", launch: false,
    regions: ["Bradford"] },
  { city: "Brant", province: "Ontario", launch: false,
    regions: ["Brant"] },
  { city: "Brantford", province: "Ontario", launch: false,
    regions: ["Brantford"] },
  { city: "Brockville", province: "Ontario", launch: false,
    regions: ["Brockville"] },
  { city: "Burlington", province: "Ontario", launch: false,
    regions: ["Burlington"] },
  { city: "Caledon", province: "Ontario", launch: false,
    regions: ["Caledon"] },
  { city: "Cambridge", province: "Ontario", launch: false,
    regions: ["Cambridge"] },
  { city: "Carleton Place", province: "Ontario", launch: false,
    regions: ["Carleton Place"] },
  { city: "Chatham-Kent", province: "Ontario", launch: false,
    regions: ["Chatham-Kent"] },
  { city: "Clarington", province: "Ontario", launch: false,
    regions: ["Clarington"] },
  { city: "Cobourg", province: "Ontario", launch: false,
    regions: ["Cobourg"] },
  { city: "Collingwood", province: "Ontario", launch: false,
    regions: ["Collingwood"] },
  { city: "Cornwall", province: "Ontario", launch: false,
    regions: ["Cornwall"] },
  { city: "East Gwillimbury", province: "Ontario", launch: false,
    regions: ["East Gwillimbury"] },
  { city: "Elliot Lake", province: "Ontario", launch: false,
    regions: ["Elliot Lake"] },
  { city: "Fort Erie", province: "Ontario", launch: false,
    regions: ["Fort Erie"] },
  { city: "Gananoque", province: "Ontario", launch: false,
    regions: ["Gananoque"] },
  { city: "Georgina", province: "Ontario", launch: false,
    regions: ["Georgina"] },
  { city: "Goderich", province: "Ontario", launch: false,
    regions: ["Goderich"] },
  { city: "Gravenhurst", province: "Ontario", launch: false,
    regions: ["Gravenhurst"] },
  { city: "Greater Sudbury", province: "Ontario", launch: false,
    regions: ["Greater Sudbury"] },
  { city: "Grimsby", province: "Ontario", launch: false,
    regions: ["Grimsby"] },
  { city: "Guelph", province: "Ontario", launch: false,
    regions: ["Guelph"] },
  { city: "Haldimand", province: "Ontario", launch: false,
    regions: ["Haldimand"] },
  { city: "Halton Hills", province: "Ontario", launch: false,
    regions: ["Halton Hills"] },
  { city: "Hamilton", province: "Ontario", launch: false,
    regions: ["Downtown Hamilton","Hamilton East End","Hamilton Mountain","Stoney Creek","Dundas","Ancaster","Flamborough","Glanbrook"] },
  { city: "Huntsville", province: "Ontario", launch: false,
    regions: ["Huntsville"] },
  { city: "Ingersoll", province: "Ontario", launch: false,
    regions: ["Ingersoll"] },
  { city: "Innisfil", province: "Ontario", launch: false,
    regions: ["Innisfil"] },
  { city: "Kenora", province: "Ontario", launch: false,
    regions: ["Kenora"] },
  { city: "Kincardine", province: "Ontario", launch: false,
    regions: ["Kincardine"] },
  { city: "King City", province: "Ontario", launch: false,
    regions: ["King City"] },
  { city: "Kingston", province: "Ontario", launch: false,
    regions: ["Kingston"] },
  { city: "Kitchener", province: "Ontario", launch: false,
    regions: ["Kitchener"] },
  { city: "London", province: "Ontario", launch: false,
    regions: ["Downtown London","North London","East London","South London","West London"] },
  { city: "Midland", province: "Ontario", launch: false,
    regions: ["Midland"] },
  { city: "Milton", province: "Ontario", launch: false,
    regions: ["Milton"] },
  { city: "Newmarket", province: "Ontario", launch: false,
    regions: ["Newmarket"] },
  { city: "Niagara Falls", province: "Ontario", launch: false,
    regions: ["Niagara Falls"] },
  { city: "Niagara-on-the-Lake", province: "Ontario", launch: false,
    regions: ["Niagara-on-the-Lake"] },
  { city: "Norfolk", province: "Ontario", launch: false,
    regions: ["Norfolk"] },
  { city: "North Bay", province: "Ontario", launch: false,
    regions: ["North Bay"] },
  { city: "Oakville", province: "Ontario", launch: false,
    regions: ["Oakville"] },
  { city: "Orillia", province: "Ontario", launch: false,
    regions: ["Orillia"] },
  { city: "Oshawa", province: "Ontario", launch: false,
    regions: ["Oshawa"] },
  { city: "Ottawa", province: "Ontario", launch: false,
    regions: ["Downtown Ottawa","Centretown","Kanata","Nepean","Barrhaven","Orleans","Gloucester","Vanier","Stittsville","Riverside South","Alta Vista"] },
  { city: "Owen Sound", province: "Ontario", launch: false,
    regions: ["Owen Sound"] },
  { city: "Parry Sound", province: "Ontario", launch: false,
    regions: ["Parry Sound"] },
  { city: "Pembroke", province: "Ontario", launch: false,
    regions: ["Pembroke"] },
  { city: "Perth", province: "Ontario", launch: false,
    regions: ["Perth"] },
  { city: "Petawawa", province: "Ontario", launch: false,
    regions: ["Petawawa"] },
  { city: "Peterborough", province: "Ontario", launch: false,
    regions: ["Peterborough"] },
  { city: "Pickering", province: "Ontario", launch: false,
    regions: ["Pickering"] },
  { city: "Port Hope", province: "Ontario", launch: false,
    regions: ["Port Hope"] },
  { city: "Quinte West", province: "Ontario", launch: false,
    regions: ["Quinte West"] },
  { city: "Renfrew", province: "Ontario", launch: false,
    regions: ["Renfrew"] },
  { city: "Sarnia", province: "Ontario", launch: false,
    regions: ["Sarnia"] },
  { city: "Sault Ste. Marie", province: "Ontario", launch: false,
    regions: ["Sault Ste. Marie"] },
  { city: "Simcoe", province: "Ontario", launch: false,
    regions: ["Simcoe"] },
  { city: "Smiths Falls", province: "Ontario", launch: false,
    regions: ["Smiths Falls"] },
  { city: "St. Catharines", province: "Ontario", launch: false,
    regions: ["St. Catharines"] },
  { city: "Stratford", province: "Ontario", launch: false,
    regions: ["Stratford"] },
  { city: "Thunder Bay", province: "Ontario", launch: false,
    regions: ["Thunder Bay"] },
  { city: "Tillsonburg", province: "Ontario", launch: false,
    regions: ["Tillsonburg"] },
  { city: "Timmins", province: "Ontario", launch: false,
    regions: ["Timmins"] },
  { city: "Walkerton", province: "Ontario", launch: false,
    regions: ["Walkerton"] },
  { city: "Wasaga Beach", province: "Ontario", launch: false,
    regions: ["Wasaga Beach"] },
  { city: "Waterloo", province: "Ontario", launch: false,
    regions: ["Waterloo"] },
  { city: "Welland", province: "Ontario", launch: false,
    regions: ["Welland"] },
  { city: "Whitby", province: "Ontario", launch: false,
    regions: ["Whitby"] },
  { city: "Whitchurch-Stouffville", province: "Ontario", launch: false,
    regions: ["Whitchurch-Stouffville"] },
  { city: "Windsor", province: "Ontario", launch: false,
    regions: ["Downtown Windsor","East Windsor","South Windsor","Riverside","Walkerville"] },
  { city: "Woodstock", province: "Ontario", launch: false,
    regions: ["Woodstock"] },
  { city: "Abbotsford", province: "British Columbia", launch: false,
    regions: ["Abbotsford West","Abbotsford East","Clearbrook"] },
  { city: "Agassiz", province: "British Columbia", launch: false,
    regions: ["Agassiz"] },
  { city: "Burnaby", province: "British Columbia", launch: false,
    regions: ["Metrotown","Brentwood","Lougheed","Edmonds"] },
  { city: "Campbell River", province: "British Columbia", launch: false,
    regions: ["Campbell River"] },
  { city: "Castlegar", province: "British Columbia", launch: false,
    regions: ["Castlegar"] },
  { city: "Central Saanich", province: "British Columbia", launch: false,
    regions: ["Central Saanich"] },
  { city: "Chilliwack", province: "British Columbia", launch: false,
    regions: ["Chilliwack"] },
  { city: "Colwood", province: "British Columbia", launch: false,
    regions: ["Colwood"] },
  { city: "Comox", province: "British Columbia", launch: false,
    regions: ["Comox"] },
  { city: "Coquitlam", province: "British Columbia", launch: false,
    regions: ["Coquitlam"] },
  { city: "Courtenay", province: "British Columbia", launch: false,
    regions: ["Courtenay"] },
  { city: "Cranbrook", province: "British Columbia", launch: false,
    regions: ["Cranbrook"] },
  { city: "Dawson Creek", province: "British Columbia", launch: false,
    regions: ["Dawson Creek"] },
  { city: "Delta", province: "British Columbia", launch: false,
    regions: ["North Delta","Ladner","Tsawwassen"] },
  { city: "Duncan", province: "British Columbia", launch: false,
    regions: ["Duncan"] },
  { city: "Esquimalt", province: "British Columbia", launch: false,
    regions: ["Esquimalt"] },
  { city: "Fernie", province: "British Columbia", launch: false,
    regions: ["Fernie"] },
  { city: "Fort St. John", province: "British Columbia", launch: false,
    regions: ["Fort St. John"] },
  { city: "Gibsons", province: "British Columbia", launch: false,
    regions: ["Gibsons"] },
  { city: "Golden", province: "British Columbia", launch: false,
    regions: ["Golden"] },
  { city: "Hope", province: "British Columbia", launch: false,
    regions: ["Hope"] },
  { city: "Kamloops", province: "British Columbia", launch: false,
    regions: ["Kamloops"] },
  { city: "Kelowna", province: "British Columbia", launch: false,
    regions: ["Kelowna"] },
  { city: "Kent", province: "British Columbia", launch: false,
    regions: ["Kent"] },
  { city: "Kimberley", province: "British Columbia", launch: false,
    regions: ["Kimberley"] },
  { city: "Kitimat", province: "British Columbia", launch: false,
    regions: ["Kitimat"] },
  { city: "Ladysmith", province: "British Columbia", launch: false,
    regions: ["Ladysmith"] },
  { city: "Langford", province: "British Columbia", launch: false,
    regions: ["Langford"] },
  { city: "Langley City", province: "British Columbia", launch: false,
    regions: ["Langley City"] },
  { city: "Langley Township", province: "British Columbia", launch: false,
    regions: ["Langley Township"] },
  { city: "Maple Ridge", province: "British Columbia", launch: false,
    regions: ["Maple Ridge"] },
  { city: "Mission", province: "British Columbia", launch: false,
    regions: ["Mission"] },
  { city: "Nanaimo", province: "British Columbia", launch: false,
    regions: ["Nanaimo"] },
  { city: "Nelson", province: "British Columbia", launch: false,
    regions: ["Nelson"] },
  { city: "New Westminster", province: "British Columbia", launch: false,
    regions: ["New Westminster"] },
  { city: "North Saanich", province: "British Columbia", launch: false,
    regions: ["North Saanich"] },
  { city: "North Vancouver City", province: "British Columbia", launch: false,
    regions: ["North Vancouver City"] },
  { city: "North Vancouver District", province: "British Columbia", launch: false,
    regions: ["North Vancouver District"] },
  { city: "Oak Bay", province: "British Columbia", launch: false,
    regions: ["Oak Bay"] },
  { city: "Parksville", province: "British Columbia", launch: false,
    regions: ["Parksville"] },
  { city: "Pemberton", province: "British Columbia", launch: false,
    regions: ["Pemberton"] },
  { city: "Penticton", province: "British Columbia", launch: false,
    regions: ["Penticton"] },
  { city: "Pitt Meadows", province: "British Columbia", launch: false,
    regions: ["Pitt Meadows"] },
  { city: "Port Alberni", province: "British Columbia", launch: false,
    regions: ["Port Alberni"] },
  { city: "Port Coquitlam", province: "British Columbia", launch: false,
    regions: ["Port Coquitlam"] },
  { city: "Port Moody", province: "British Columbia", launch: false,
    regions: ["Port Moody"] },
  { city: "Powell River", province: "British Columbia", launch: false,
    regions: ["Powell River"] },
  { city: "Prince George", province: "British Columbia", launch: false,
    regions: ["Prince George"] },
  { city: "Prince Rupert", province: "British Columbia", launch: false,
    regions: ["Prince Rupert"] },
  { city: "Qualicum Beach", province: "British Columbia", launch: false,
    regions: ["Qualicum Beach"] },
  { city: "Quesnel", province: "British Columbia", launch: false,
    regions: ["Quesnel"] },
  { city: "Revelstoke", province: "British Columbia", launch: false,
    regions: ["Revelstoke"] },
  { city: "Richmond", province: "British Columbia", launch: false,
    regions: ["Richmond City Centre","Steveston"] },
  { city: "Saanich", province: "British Columbia", launch: false,
    regions: ["Saanich"] },
  { city: "Salmon Arm", province: "British Columbia", launch: false,
    regions: ["Salmon Arm"] },
  { city: "Sechelt", province: "British Columbia", launch: false,
    regions: ["Sechelt"] },
  { city: "Sidney", province: "British Columbia", launch: false,
    regions: ["Sidney"] },
  { city: "Smithers", province: "British Columbia", launch: false,
    regions: ["Smithers"] },
  { city: "Sooke", province: "British Columbia", launch: false,
    regions: ["Sooke"] },
  { city: "Squamish", province: "British Columbia", launch: false,
    regions: ["Squamish"] },
  { city: "Surrey", province: "British Columbia", launch: false,
    regions: ["Surrey City Centre","Guildford","Fleetwood","Newton","Cloverdale","South Surrey"] },
  { city: "Terrace", province: "British Columbia", launch: false,
    regions: ["Terrace"] },
  { city: "Trail", province: "British Columbia", launch: false,
    regions: ["Trail"] },
  { city: "Vancouver", province: "British Columbia", launch: false,
    regions: ["Arbutus-Ridge","Downtown","Dunbar-Southlands","Fairview","Grandview-Woodland","Hastings-Sunrise","Kensington-Cedar Cottage","Kerrisdale","Killarney","Kitsilano","Marpole","Mount Pleasant","Oakridge","Renfrew-Collingwood","Riley Park","Shaughnessy","South Cambie","Strathcona","Sunset","Victoria-Fraserview","West End","West Point Grey"] },
  { city: "Vernon", province: "British Columbia", launch: false,
    regions: ["Vernon"] },
  { city: "Victoria", province: "British Columbia", launch: false,
    regions: ["Downtown Victoria","James Bay","Fairfield","Fernwood","Vic West","Rockland"] },
  { city: "View Royal", province: "British Columbia", launch: false,
    regions: ["View Royal"] },
  { city: "West Kelowna", province: "British Columbia", launch: false,
    regions: ["West Kelowna"] },
  { city: "West Vancouver", province: "British Columbia", launch: false,
    regions: ["West Vancouver"] },
  { city: "Whistler", province: "British Columbia", launch: false,
    regions: ["Whistler"] },
  { city: "White Rock", province: "British Columbia", launch: false,
    regions: ["White Rock"] },
  { city: "Williams Lake", province: "British Columbia", launch: false,
    regions: ["Williams Lake"] },
];

/** 'North York Central' -> 'north-york-central'. The console's own slug rule,
    and the one coverage_key and every region comparison already use. */
function slug(s) {
  return String(s || '').trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

/* Built once: this module is required per request and the list does not move. */
const BY_SLUG = new Map();
for (const place of PLACES) {
  for (const region of place.regions) {
    const key = slug(region);
    /* 'West End' exists in Toronto and Vancouver. The launch city wins, the
       same resolution partner/core/places.js placeOf() makes, and for the same
       reason: it is the only one of the two running cohorts. */
    const held = BY_SLUG.get(key);
    if (!held || (place.launch && !held.place.launch)) BY_SLUG.set(key, { region, place });
  }
}

/** The vocabulary entry for a region name, or null. Matching is on the slug,
    so casing and punctuation do not decide whether a cohort is reachable. */
function lookup(region) {
  const key = slug(region);
  return key ? (BY_SLUG.get(key) || null) : null;
}

/** The city record a region sits in, or null when the name is not ours. */
function placeOf(region) {
  const hit = lookup(region);
  return hit ? hit.place : null;
}

/** Is this a name any partner could pick? */
function isRegion(region) {
  return lookup(region) !== null;
}

/** Is this a name a partner could pick AND declare today? */
function isLaunchRegion(region) {
  const hit = lookup(region);
  return Boolean(hit && hit.place.launch);
}

/** The canonical spelling, so a row stores 'Scarborough Centre' whatever case
    the caller sent. One spelling in the table is what keeps a later exact
    comparison honest. */
function canonical(region) {
  const hit = lookup(region);
  return hit ? hit.region : null;
}

/**
 * The closest names we do have, for the refusal message. A 400 that says only
 * "not a region" makes an operator guess; one that says "did you mean
 * Vaughan Woodbridge" ends the problem in one read.
 *
 * Token overlap, not edit distance: the mistakes this actually sees are a real
 * place with the wrong subdivision ('Vaughan West', 'Mississauga Core'), and
 * the shared token is what finds them.
 */
function suggest(region, limit = 3) {
  const want = slug(region).split('-').filter(Boolean);
  if (!want.length) return [];
  const scored = [];
  for (const { region: name, place } of BY_SLUG.values()) {
    const have = slug(name).split('-').filter(Boolean);
    let score = 0;
    for (const token of want) if (have.includes(token)) score += token.length;
    /* A launch region outranks a queued one on a tie: 'Vaughan West' should
       offer Vaughan's own subdivisions before Abbotsford West, which shares a
       token and nothing else. */
    if (score) scored.push({ name, score, launch: place.launch });
  }
  scored.sort((a, b) =>
    b.score - a.score || (b.launch ? 1 : 0) - (a.launch ? 1 : 0) || a.name.localeCompare(b.name));
  return scored.slice(0, limit).map((s) => s.name);
}

/** Every declarable name, sorted. Used by the ZCQL tool to print the list. */
function launchRegions() {
  return PLACES.filter((p) => p.launch)
    .flatMap((p) => p.regions)
    .sort((a, b) => a.localeCompare(b));
}

module.exports = {
  PLACES, slug, placeOf, isRegion, isLaunchRegion, canonical, suggest, launchRegions,
};
