#!/usr/bin/env node
/* Give the SERVER the coverage vocabulary the browser already has.
 *
 *   node scripts/build-places.mjs           write the backend copy
 *   node scripts/build-places.mjs --check   fail if it is stale (CI)
 *
 * WHY THIS EXISTS. The declared region name is the only thing joining the two
 * dashboards. routes/desk.js requireActiveCoverage() matches a bid to coverage
 * with slug(row.region) === slug(campaign.region), an exact comparison, server
 * side, on the region alone. partner/core/places.js is the list a partner may
 * pick from, and scripts/test-places.mjs already holds every shipped region
 * name to it.
 *
 * None of that reaches the write path. POST /admin/campaigns validated `region`
 * as "present, under 100 characters" and nothing else, so a cohort could be
 * created naming "Vaughan West" or "Mississauga Core", names no partner can
 * declare, and it would render perfectly on both dashboards while matching
 * nothing and taking no bid, forever. The failure is silent in the worst way:
 * it looks like a quiet market rather than a typo.
 *
 * So the vocabulary crosses to the backend as data. partner/core/places.js
 * stays the source, because it is also the picker, and one list with a
 * generator beats two lists with a convention.
 *
 * WHY GENERATE RATHER THAN SHARE. The backend is CommonJS inside a Catalyst
 * function with its own package.json and its own node_modules; the console is
 * ES modules compiled by build-console.mjs. Neither can require the other, and
 * a runtime fetch of a static list would be a network call to answer a question
 * that is decided at build time. A generated file with a --check gate is the
 * same trade every other generated file here makes.
 *
 * The emitted module is DATA plus pure functions. It never touches the Data
 * Store, so it stays unit-testable from scripts/ through backend-module.mjs.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { PLACES } from '../partner/core/places.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = 'partner/core/places.js';
const OUT = join(ROOT, 'catalyst-backend/functions/auth/src/lib/places.js');

const check = process.argv.includes('--check');

/* ------------------------------------------------------------------ *
 * emit
 * ------------------------------------------------------------------ */

/** One city per line, the shape the source file uses, so a diff reads. */
function placesLiteral(places) {
  return places.map((p) =>
    `  { city: ${JSON.stringify(p.city)}, province: ${JSON.stringify(p.province)}, `
    + `launch: ${p.launch ? 'true' : 'false'},\n`
    + `    regions: ${JSON.stringify(p.regions)} },`
  ).join('\n');
}

const regionCount = PLACES.reduce((n, p) => n + p.regions.length, 0);
const launchCount = PLACES.filter((p) => p.launch).length;

const body = `'use strict';

/**
 * GENERATED by scripts/build-places.mjs from ${SRC}. Do NOT edit by hand.
 * Run the generator and commit the result, or the --check gate reports STALE.
 *
 * The declarable coverage vocabulary, server side. ${regionCount} regions across
 * ${PLACES.length} cities, ${launchCount} of them launched.
 *
 * WHAT IT IS FOR. The region name is the whole join between a cohort and a
 * partner: requireActiveCoverage() in routes/desk.js compares
 * slug(coverage.region) to slug(campaign.region) exactly. A campaign created
 * with a name outside this list is a campaign no partner can ever bid on, and
 * nothing about it looks broken until the auction closes with no bids. The
 * picker constrains one side of that in the browser; this file is what lets the
 * write path constrain the other side, where it counts.
 *
 * LAUNCH IS NOT DECORATION. The picker offers only launch-city regions as
 * selectable, so a cohort in a queued city cannot be declared against by
 * anyone. Campaign creation therefore requires a launch region; declaring
 * coverage requires only a known one, because a partner may register interest
 * in a queued city and an operator leaves that row 'soon'.
 */

const PLACES = [
${placesLiteral(PLACES)}
];

/** 'North York Central' -> 'north-york-central'. The console's own slug rule,
    and the one coverage_key and every region comparison already use. */
function slug(s) {
  return String(s || '').trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

/* Built once: this module is required per request and the list does not move. */
const BY_SLUG = new Map();
for (const place of PLACES) {
  for (const region of place.regions) {
    const key = slug(region);
    /* 'West End' exists in Toronto and Vancouver. The launch city wins, the
       same resolution partner/core/places.js placeOf() makes, and for the same
       reason: it is the only one of the two running cohorts. */
    const held = BY_SLUG.get(key);
    if (!held || (place.launch && !held.place.launch)) BY_SLUG.set(key, { region, place });
  }
}

/** The vocabulary entry for a region name, or null. Matching is on the slug,
    so casing and punctuation do not decide whether a cohort is reachable. */
function lookup(region) {
  const key = slug(region);
  return key ? (BY_SLUG.get(key) || null) : null;
}

/** The city record a region sits in, or null when the name is not ours. */
function placeOf(region) {
  const hit = lookup(region);
  return hit ? hit.place : null;
}

/** Is this a name any partner could pick? */
function isRegion(region) {
  return lookup(region) !== null;
}

/** Is this a name a partner could pick AND declare today? */
function isLaunchRegion(region) {
  const hit = lookup(region);
  return Boolean(hit && hit.place.launch);
}

/** The canonical spelling, so a row stores 'Scarborough Centre' whatever case
    the caller sent. One spelling in the table is what keeps a later exact
    comparison honest. */
function canonical(region) {
  const hit = lookup(region);
  return hit ? hit.region : null;
}

/**
 * The closest names we do have, for the refusal message. A 400 that says only
 * "not a region" makes an operator guess; one that says "did you mean
 * Vaughan Woodbridge" ends the problem in one read.
 *
 * Token overlap, not edit distance: the mistakes this actually sees are a real
 * place with the wrong subdivision ('Vaughan West', 'Mississauga Core'), and
 * the shared token is what finds them.
 */
function suggest(region, limit = 3) {
  const want = slug(region).split('-').filter(Boolean);
  if (!want.length) return [];
  const scored = [];
  for (const { region: name, place } of BY_SLUG.values()) {
    const have = slug(name).split('-').filter(Boolean);
    let score = 0;
    for (const token of want) if (have.includes(token)) score += token.length;
    /* A launch region outranks a queued one on a tie: 'Vaughan West' should
       offer Vaughan's own subdivisions before Abbotsford West, which shares a
       token and nothing else. */
    if (score) scored.push({ name, score, launch: place.launch });
  }
  scored.sort((a, b) =>
    b.score - a.score || (b.launch ? 1 : 0) - (a.launch ? 1 : 0) || a.name.localeCompare(b.name));
  return scored.slice(0, limit).map((s) => s.name);
}

/** Every declarable name, sorted. Used by the ZCQL tool to print the list. */
function launchRegions() {
  return PLACES.filter((p) => p.launch)
    .flatMap((p) => p.regions)
    .sort((a, b) => a.localeCompare(b));
}

module.exports = {
  PLACES, slug, placeOf, isRegion, isLaunchRegion, canonical, suggest, launchRegions,
};
`;

/* ------------------------------------------------------------------ *
 * write or check
 * ------------------------------------------------------------------ */

if (check) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (current !== body) {
    console.error('build-places: STALE\n');
    console.error('  catalyst-backend/functions/auth/src/lib/places.js');
    console.error(`\nRun: node scripts/build-places.mjs, then commit the result.`);
    process.exit(1);
  }
  console.log(`build-places: OK, ${regionCount} regions across ${PLACES.length} cities`);
} else {
  writeFileSync(OUT, body);
  console.log(`build-places: wrote catalyst-backend/functions/auth/src/lib/places.js`);
  console.log(`  ${regionCount} regions, ${PLACES.length} cities, ${launchCount} launched`);
}
