#!/usr/bin/env node
/* Give the SERVER the speed ladder the console already has.
 *
 *   node scripts/build-tiers.mjs           write the backend copy
 *   node scripts/build-tiers.mjs --check   fail if it is stale (CI)
 *
 * Same trade as scripts/build-mixmath.mjs, for the same reason: the backend is
 * CommonJS inside a Catalyst function, the console is ES modules compiled by
 * build-console.mjs, and neither can require the other. partner/core/tiers.js
 * is the source; this emits catalyst-backend/.../lib/tiers.js. The transform
 * is text and deliberately dumb: `export function` becomes `function`,
 * `export var` becomes `var`, and every exported name lands in module.exports.
 * That only works because the source has no imports, which is a constraint on
 * tiers.js, stated at its top.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = 'partner/core/tiers.js';
const OUT_REL = 'catalyst-backend/functions/auth/src/lib/tiers.js';
const OUT = join(ROOT, OUT_REL);
const check = process.argv.includes('--check');

const source = readFileSync(join(ROOT, SRC), 'utf8');
if (/^\s*import\b/m.test(source)) {
  console.error(`build-tiers: ${SRC} has an import, and the transform cannot carry one. Keep it standalone.`);
  process.exit(1);
}

const names = [];
const body = source
  .replace(/^export (function|var) ([A-Za-z_$][\w$]*)/gm, (m, kind, name) => {
    names.push(name);
    return `${kind} ${name}`;
  })
  .replace(/^export\b/m, () => {
    console.error('build-tiers: an export form the transform does not know. Use `export function` or `export var`.');
    process.exit(1);
  });

const out = `'use strict';

/**
 * GENERATED by scripts/build-tiers.mjs from ${SRC}. Do NOT edit by hand.
 * Run the generator and commit the result, or the --check gate reports STALE.
 *
 * The standard speed ladder, server side: the same labels a bid is validated
 * against, the same snap a household's window centres on, and the same Mbps
 * the cohort's speed demand is counted with.
 */

${body.replace(/^\/\*[\s\S]*?\*\/\n\n/, '')}
module.exports = {
  ${names.join(', ')}
};
`;

if (check) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (current !== out) {
    console.error('build-tiers: STALE\n');
    console.error(`  ${OUT_REL}`);
    console.error('\nRun: node scripts/build-tiers.mjs, then commit the result.');
    process.exit(1);
  }
  console.log(`build-tiers: OK, ${names.length} exports`);
} else {
  writeFileSync(OUT, out);
  console.log(`build-tiers: wrote ${OUT_REL}`);
  console.log(`  ${names.length} exports: ${names.join(', ')}`);
}
