#!/usr/bin/env node
/* Generate the shared site footer into every page.
 *
 * WHY
 * The footer was hand-copied into each page, so it drifted: /partners still
 * linked "Company", "LinkedIn" and "Legal" at href="#", the blog pages carried
 * a one-line copyright with no navigation at all, and the checkout-ish pages
 * (waitlist, thank-you, logins, dashboards) had no footer whatsoever. Editing
 * the nav meant finding and re-typing it in 35 files, which is exactly how the
 * dead links survived. The footer is now defined once, here, and written into
 * every page between markers.
 *
 *   node scripts/build-footer.mjs          # write the footer into every page
 *   node scripts/build-footer.mjs --check  # CI: fail if any page is stale
 *
 * ORDER
 * Run this BEFORE scripts/build-mobile-pages.mjs: bill-checkup-mobile and
 * become-a-partner-mobile are generated from their desktop sources, so they
 * inherit the footer (and its mobile link rewrites) from there rather than
 * being listed below.
 *
 * The markup is deliberately self-contained, its own colours, spacing and
 * font stack, because it drops into four unrelated design systems (the site
 * pages, the cream legal pages, the serif blog and the provider deck). It must
 * not depend on a page defining --navy-deep, --disp or any other token.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');

const CSS_START = '<!-- WHOLLAR-FOOTER-CSS:START (generated by scripts/build-footer.mjs) -->';
const CSS_END = '<!-- WHOLLAR-FOOTER-CSS:END -->';
const HTML_START = '<!-- WHOLLAR-FOOTER:START (generated by scripts/build-footer.mjs) -->';
const HTML_END = '<!-- WHOLLAR-FOOTER:END -->';

const CSS = `${CSS_START}
<style id="whl-footer-css">
.whl-footer{margin:0;background:#0A2018;color:#CFE8D6;border-top:1px solid rgba(255,255,255,.08);padding:40px 0 calc(30px + env(safe-area-inset-bottom));font-family:Inter,'IBM Plex Sans',system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;font-size:14.5px;line-height:1.5;text-align:left}
.whl-footer__wrap{max-width:1340px;margin:0 auto;padding:0 24px}
.whl-footer__top{display:grid;grid-template-columns:1fr auto 1fr;gap:28px;align-items:start;padding-bottom:30px;border-bottom:1px solid rgba(255,255,255,.12)}
.whl-footer__brand{max-width:340px}
.whl-footer__row{display:flex;align-items:center;gap:10px;margin-bottom:12px}
.whl-footer__mk{width:30px;height:30px;border-radius:9px;flex:none;display:block}
.whl-footer__wm{font-family:'Satoshi','Hanken Grotesk','Bricolage Grotesque',Inter,system-ui,sans-serif;font-weight:800;font-size:20px;letter-spacing:-.01em;color:#fff}
.whl-footer__brand p{margin:0;font-size:14px;line-height:1.5;color:#9FC1BF;font-style:normal;white-space:nowrap}
.whl-footer__cols{display:flex;gap:96px;flex-wrap:wrap;margin:0 auto}
.whl-footer__col{display:flex;flex-direction:column;gap:11px}
.whl-footer__col a{color:#CFE8D6;text-decoration:none;font-size:14.5px;font-weight:400;border:0}
.whl-footer__col a:hover{color:#fff}
.whl-footer__col a[aria-current="page"]{color:#fff;font-weight:600}
.whl-footer__bottom{display:flex;flex-wrap:wrap;gap:14px;justify-content:space-between;align-items:center;padding-top:22px}
.whl-footer__bottom span{font-size:13px;color:#8FB39B}
.whl-footer__made{display:inline-flex;align-items:center;gap:7px;font-size:13px;color:#CFE8D6;font-weight:600}
@media(max-width:880px){
  .whl-footer__top{display:flex;flex-wrap:wrap;justify-content:space-between;align-items:flex-start}
  .whl-footer__cols{gap:48px;margin:0}
}
@media(max-width:560px){.whl-footer__cols{gap:34px}}
@media(max-width:380px){.whl-footer__brand p{font-size:11.5px}}
</style>
${CSS_END}`;

const MARK = '<svg class="whl-footer__mk" width="30" height="30" viewBox="0 0 120 120" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Whollar">' +
  '<defs><linearGradient id="whlFooterMark" x1="18" y1="14" x2="102" y2="106" gradientUnits="userSpaceOnUse">' +
  '<stop offset="0" stop-color="#0E2A20"/><stop offset="1" stop-color="#1E9E63"/></linearGradient></defs>' +
  '<rect x="6" y="6" width="108" height="108" rx="32" fill="url(#whlFooterMark)"/>' +
  '<path d="M34 42h52M34 42l26 38M86 42l-26 38" stroke="#FFFFFF" stroke-width="5" stroke-linecap="round" stroke-linejoin="round" opacity=".85"/>' +
  '<circle cx="34" cy="42" r="11" fill="#FFFFFF"/><circle cx="86" cy="42" r="11" fill="#FFFFFF"/>' +
  '<circle cx="60" cy="80" r="11" fill="#FFFFFF"/></svg>';

const LEAF = '<svg width="15" height="15" viewBox="0 0 24 24" fill="#1E9E63" aria-hidden="true">' +
  '<path d="M12 2l1.6 4.3 4.4-1.2-2 4 3.5 2.4-4 1.3.6 4.4-3.7-2.2L12 22l-.4-3.3-3.7 2.2.6-4.4-4-1.3L4 9.1l-2-4 4.4 1.2z"/></svg>';

/* Desktop routes. Mobile pages override the four that have a mobile twin;
   /contact, /privacy and /terms have none and are shared. */
const DESKTOP = {
  home: '/', how: '/#how', why: '/#why', faq: '/#faq',
  resources: '/blog/', contact: '/contact',
  privacy: '/privacy', terms: '/terms', providers: '/partners'
};
const MOBILE = {
  ...DESKTOP,
  home: '/MobileVersion/consumer-mobile',
  how: '/MobileVersion/consumer-mobile#how',
  why: '/MobileVersion/consumer-mobile#why',
  faq: '/MobileVersion/consumer-mobile#faq',
  resources: '/MobileVersion/resources-mobile',
  providers: '/MobileVersion/provider-mobile'
};
/* The two pages that own #how/#why/#faq link to them in-page rather than
   bouncing through a full navigation. */
const SELF_ANCHORS = { how: '#how', why: '#why', faq: '#faq' };

function html(routes, current) {
  const link = (key, label) => {
    const cur = key === current ? ' aria-current="page"' : '';
    return `        <a href="${routes[key]}"${cur}>${label}</a>`;
  };
  return `${HTML_START}
<footer class="whl-footer">
  <div class="whl-footer__wrap">
    <div class="whl-footer__top">
      <div class="whl-footer__brand">
        <div class="whl-footer__row">${MARK}<span class="whl-footer__wm">Whollar</span></div>
        <p>Wholesale buying power that saves you dollars</p>
      </div>
      <div class="whl-footer__cols">
        <div class="whl-footer__col">
${link('how', 'How it works')}
${link('why', 'Why us')}
${link('faq', 'FAQ')}
${link('resources', 'Resources')}
${link('contact', 'Contact')}
        </div>
        <div class="whl-footer__col">
${link('privacy', 'Privacy')}
${link('terms', 'Terms')}
${link('providers', 'For providers')}
        </div>
      </div>
    </div>
    <div class="whl-footer__bottom">
      <span>&copy; 2026 Whollar, now forming the first cohorts.</span>
      <span class="whl-footer__made">Made in Canada
        ${LEAF}
      </span>
    </div>
  </div>
</footer>
${HTML_END}`;
}

const BLOG_SLUGS = [
  'overpaying-internet-canada', 'internet-price-increase-promo-cliff',
  'collective-switching-internet-canada', 'teksavvy-vs-rogers-same-cable',
  'internet-bill-breakdown-canada', 'negotiate-internet-bill-canada',
  'internet-retention-offer-win-back', 'independent-internet-providers-canada',
  'collective-switching-energy-proof', 'big-three-telecom-canada',
  'crtc-internet-prices-canada', 'cheap-internet-chatham-ontario',
  'best-internet-toronto',
  'internet-speed-how-much-need',
  'rural-internet-ontario',
  'internet-providers-mississauga'
];

/* current: which nav link is marked aria-current on this page. */
const PAGES = [
  { file: 'index.html', current: 'home', self: true },
  { file: 'contact.html', current: 'contact' },
  { file: 'terms.html', current: 'terms' },
  { file: 'privacy.html', current: 'privacy' },
  { file: 'partners.html', current: 'providers' },
  { file: 'become-a-partner.html', current: 'providers' },
  { file: 'bill-checkup.html', current: null },
  { file: 'waitlist/index.html', current: null },
  { file: 'thank-you.html', current: null },
  /* The region pages. A cohort page is a marketing page for one address, so
     it carries the footer like every other public page: nobody is signed in
     here, and the route back out to /bill-checkup, /privacy and /contact is
     the point rather than a leak. `current: null` because there is no nav
     item for a region. */
  { file: 'greystonewalk.html', current: null },
  /* The ported landing design, staged for review at /landing. At cutover it
     replaces index.html and this line inherits index's entry. */
  { file: 'landing.html', current: null },
  /* NO FOOTER ON A SIGNED-IN SURFACE. dashboard.html, partner/index.html,
     welcome-member.html and welcome-partner.html are app chrome, not marketing
     pages: a member or a partner who has signed in is inside the product, and
     a marketing footer under the console is a route back out of it. The two
     welcome screens are the first thing a new account sees and their whole job
     is the single CTA onward, which twenty footer links compete with. The login
     pages keep theirs, because nobody is signed in yet. Deliberately absent
     from this list, and the footer markers are stripped from those files, so
     `--check` has nothing to call stale. */
  /* join.html is deliberately absent for the same reason as the welcome
     screens above: it is a single-purpose signup, its whole job is the one
     form, and it already carries Terms and Privacy in the consent line. It
     also has no footer markers, so --check has nothing to call stale. */
  { file: 'whollar-login-consumer.html', current: null },
  { file: 'whollar-login-provider.html', current: null },
  { file: 'blog/index.html', current: 'resources' },
  ...BLOG_SLUGS.map(s => ({ file: `blog/${s}/index.html`, current: 'resources' })),

  { file: 'MobileVersion/consumer-mobile.html', current: 'home', mobile: true, self: true },
  { file: 'MobileVersion/provider-mobile.html', current: 'providers', mobile: true },
  { file: 'MobileVersion/resources-mobile.html', current: 'resources', mobile: true },
  { file: 'MobileVersion/join-the-first-cohort-mobile.html', current: null, mobile: true },
  ...BLOG_SLUGS.map(s => ({ file: `MobileVersion/blog/${s}.html`, current: 'resources', mobile: true }))
];

function between(s, start, end) {
  const a = s.indexOf(start);
  if (a === -1) return null;
  const b = s.indexOf(end, a);
  if (b === -1) throw new Error(`opening marker without its closing pair: ${start}`);
  return [a, b + end.length];
}

function build(page) {
  const path = join(ROOT, page.file);
  if (!existsSync(path)) throw new Error(`missing page ${page.file}`);
  let s = readFileSync(path, 'utf8');

  const routes = { ...(page.mobile ? MOBILE : DESKTOP), ...(page.self ? SELF_ANCHORS : {}) };
  const markup = html(routes, page.current);

  /* CSS goes last in <head> so it outranks the page's own stylesheet without
     needing !important against four different sets of base `a` rules. */
  const cssSpan = between(s, CSS_START, CSS_END);
  if (cssSpan) {
    s = s.slice(0, cssSpan[0]) + CSS + s.slice(cssSpan[1]);
  } else {
    if (!s.includes('</head>')) throw new Error(`${page.file}: no </head>`);
    s = s.replace('</head>', `${CSS}\n</head>`);
  }

  const htmlSpan = between(s, HTML_START, HTML_END);
  if (htmlSpan) {
    s = s.slice(0, htmlSpan[0]) + markup + s.slice(htmlSpan[1]);
  } else {
    /* First run: take over whatever footer the page already had, in place, so
       the document structure (e.g. /partners' x-dc wrapper) is preserved. */
    const old = s.match(/[ \t]*<footer[\s\S]*?<\/footer>/);
    if (old) {
      s = s.slice(0, old.index) + markup + s.slice(old.index + old[0].length);
    } else if (s.includes('</body>')) {
      s = s.replace('</body>', `${markup}\n</body>`);
    } else {
      throw new Error(`${page.file}: no <footer> and no </body>`);
    }
  }
  return { path, next: s };
}

let stale = 0;
let written = 0;
for (const page of PAGES) {
  const { path, next } = build(page);
  const prev = readFileSync(path, 'utf8');
  if (prev === next) continue;
  if (CHECK) {
    console.error(`STALE   ${page.file}: regenerate with: node scripts/build-footer.mjs`);
    stale++;
    continue;
  }
  writeFileSync(path, next);
  console.log(`written ${page.file}`);
  written++;
}

if (CHECK && stale) {
  console.error(`\n${stale} page(s) have a stale footer.`);
  process.exit(1);
}
console.log(CHECK
  ? `ok      ${PAGES.length} page(s) carry the current footer`
  : `\n${written} page(s) updated, ${PAGES.length} total.`);
