#!/usr/bin/env node
/* Give the SERVER the FSA reference the browser already has.
 *
 *   node scripts/build-fsa-ref.mjs           write the backend copy
 *   node scripts/build-fsa-ref.mjs --check   fail if it is stale (CI)
 *
 * WHY THIS EXISTS. Campaign eligibility is keyed on the FSA, so two write
 * paths need to know whether an FSA is real:
 *
 *   routes/admin.js  refuses "M9Z" when an operator adds it to a campaign,
 *                    because an FSA nobody lives in is a cohort nobody can
 *                    join, and it looks exactly like a cohort nobody wants.
 *   lib/geo.js       orders the rail by city then province (nearbyTier), and
 *                    an FSA with no reference row falls to the last tier
 *                    rather than crashing the read.
 *
 * The browser has held this since 2026-08-07 as js/whollar-fsa-cities.js,
 * generated by scripts/build-fsa-cities.mjs from GeoNames. Two lists with a
 * convention would drift; one list with a generator does not. Same trade, same
 * --check gate, as scripts/build-places.mjs makes for the coverage vocabulary.
 *
 * WHAT IT IS NOT. Not the authoritative Canada Post file (that one is
 * licensed), and not a validity oracle for a HOUSEHOLD's postal code. Signup
 * deliberately does not check a member's FSA against this list: a structurally
 * valid FSA missing from a free dataset would otherwise refuse a real person
 * an account. It is checked only where an operator types an FSA, which is
 * where a typo is a typo and a human is present to fix it. See the caveats in
 * js/whollar-fsa-cities.coverage.txt, which this file inherits whole.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = 'js/whollar-fsa-cities.js';
const OUT = join(ROOT, 'catalyst-backend/functions/auth/src/lib/fsaref.js');

const check = process.argv.includes('--check');

/* ---------- load the browser file ---------- */

/* The source is a classic script that attaches to a global, so it is executed
   against a bare sandbox rather than parsed. Same loader as
   scripts/build-signal-lookup.mjs, which has read this file the same way since
   it shipped. Node build script, never the browser: the no-eval rule in
   CLAUDE.md is about what a page loads, and no page loads this. */
function loadSource() {
  const code = readFileSync(join(ROOT, SRC), 'utf8');
  const sandbox = {};
  sandbox.window = sandbox;
  new Function('window', 'globalThis', code + '\nreturn window;')(sandbox, sandbox);
  const W = sandbox.WHOLLAR;
  if (!W || !W.FSA_CITY) throw new Error(`${SRC} did not define WHOLLAR.FSA_CITY`);
  return { table: W.FSA_CITY, meta: W.FSA_CITY_META || {} };
}

const { table, meta } = loadSource();

const fsas = Object.keys(table).sort();
const provinces = new Map();
for (const f of fsas) {
  const p = table[f].province;
  provinces.set(p, (provinces.get(p) || 0) + 1);
}
const byProvince = Array.from(provinces.entries()).sort()
  .map(([p, n]) => `${p}=${n}`).join(', ');

/* ---------- emit ---------- */

/* Ten FSAs a line. The whole point of a generated file is that its diff is
   readable when the source data changes; one 60KB line is not a diff. */
function tableLiteral() {
  const lines = [];
  for (let i = 0; i < fsas.length; i += 10) {
    lines.push('  ' + fsas.slice(i, i + 10)
      .map((f) => `${f}:${JSON.stringify(table[f].city + '|' + table[f].province)}`)
      .join(','));
  }
  return lines.join(',\n');
}

const body = `'use strict';

/**
 * GENERATED by scripts/build-fsa-ref.mjs from ${SRC}. Do NOT edit by hand.
 * Run the generator and commit the result, or the --check gate reports STALE.
 *
 * The FSA reference, server side: ${fsas.length} forward sortation areas with the
 * municipality and province each one sits in.
 *
 * Source: ${meta.source || 'GeoNames.org'}
 * License: ${meta.license || 'CC BY 4.0'}
 * Built from that export on ${meta.builtOn || 'unknown date'}.
 *
 * By province: ${byProvince}.
 *
 * WHAT IT IS FOR. Two things and no others:
 *
 *   has(fsa)     the operator gate. routes/admin.js refuses an FSA that is not
 *                in here when a campaign's coverage is edited, because an FSA
 *                nobody lives in is a cohort nobody can join and it looks
 *                identical to a cohort nobody wants.
 *
 *   lookup(fsa)  the rail's ORDER, via geo.nearbyTier: same city, then same
 *                province, then everything else. Ordering only. It never
 *                grants or denies a join, and a missing row costs a campaign
 *                its place in the sort and nothing more.
 *
 * IT IS NOT CHECKED AGAINST A MEMBER'S OWN POSTAL CODE, deliberately. This is
 * a best-effort free-tier mapping, not the Canada Post file, and refusing a
 * household an account because a free dataset has not heard of its FSA would
 * be this file deciding something it is not good enough to decide. A
 * structurally valid FSA that matches no campaign simply yields no
 * eligibility, which is the honest answer and already the common one.
 *
 * INHERITED CAVEATS, from js/whollar-fsa-cities.coverage.txt: GeoNames groups
 * some genuinely distinct municipalities under one metro label (North
 * Vancouver and West Vancouver FSAs both report "Vancouver"), and a few rural
 * FSAs report a district rather than a town. Both affect the city tier of the
 * rail's ordering and nothing else in this stack.
 */

/* "City|PROVINCE", packed: two fields per FSA across ${fsas.length} rows is 3300
   short strings on every cold start otherwise, for a table read a few times a
   request. Split once, on the lookup that needs it. */
const FSA = {
${tableLiteral()},
};

/** Is this a forward sortation area anybody lives in? */
const has = (fsa) => Object.prototype.hasOwnProperty.call(
  FSA, String(fsa == null ? '' : fsa).toUpperCase()
);

/** -> { fsa, city, province } or null. Never throws on an unknown FSA. */
function lookup(fsa) {
  const key = String(fsa == null ? '' : fsa).toUpperCase();
  const packed = Object.prototype.hasOwnProperty.call(FSA, key) ? FSA[key] : null;
  if (!packed) return null;
  const cut = packed.lastIndexOf('|');
  return { fsa: key, city: packed.slice(0, cut), province: packed.slice(cut + 1) };
}

/** Every FSA the reference knows, sorted. For the admin console's picker. */
const all = () => Object.keys(FSA);

const META = Object.freeze({
  source: ${JSON.stringify(meta.source || 'GeoNames.org')},
  license: ${JSON.stringify(meta.license || 'CC BY 4.0')},
  builtOn: ${JSON.stringify(meta.builtOn || null)},
  count: ${fsas.length},
});

module.exports = { has, lookup, all, META, COUNT: ${fsas.length} };
`;

/* ---------- write or check ---------- */

if (check) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (current !== body) {
    console.error(`STALE: ${OUT} does not match ${SRC}.`);
    console.error('Run: node scripts/build-fsa-ref.mjs   and commit the result.');
    process.exit(1);
  }
  console.log(`OK: fsaref.js is current (${fsas.length} FSAs).`);
} else {
  writeFileSync(OUT, body);
  console.log(`Wrote ${OUT} (${fsas.length} FSAs, ${byProvince}).`);
}
