#!/usr/bin/env node
/* Give the SERVER the mix arithmetic the browser already has.
 *
 *   node scripts/build-mixmath.mjs           write the backend copy
 *   node scripts/build-mixmath.mjs --check   fail if it is stale (CI)
 *
 * WHY THIS EXISTS. A custom mix splits a tier's reduction into named cents,
 * and two parties compute those cents: the console, live, as the partner
 * types, and the server, once, as it seals. If the two ever disagree by a
 * cent, the panel a partner confirmed and the record a household reads are
 * different documents. So the arithmetic is written once, in
 * partner/core/mixmath.js, and this script emits the CommonJS copy the
 * Catalyst function requires.
 *
 * WHY GENERATE RATHER THAN SHARE. Same trade as build-places.mjs: the backend
 * is CommonJS inside a Catalyst function with its own package.json, the
 * console is ES modules compiled by build-console.mjs, and neither can
 * require the other. A generated file with a --check gate is the same trade
 * every other generated file here makes.
 *
 * THE TRANSFORM IS TEXT, and deliberately dumb: `export function` becomes
 * `function`, `export var` becomes `var`, and every exported name lands in
 * module.exports. That only works because the source has no imports and no
 * other syntax, which is a constraint on mixmath.js, stated at its top.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = 'partner/core/mixmath.js';
const OUT = join(ROOT, 'catalyst-backend/functions/auth/src/lib/mixmath.js');
const check = process.argv.includes('--check');

const source = readFileSync(join(ROOT, SRC), 'utf8');
if (/^\s*import\b/m.test(source)) {
  console.error(`build-mixmath: ${SRC} has an import, and the transform cannot carry one. Keep it standalone.`);
  process.exit(1);
}

const names = [];
const body = source
  .replace(/^export (function|var) ([A-Za-z_$][\w$]*)/gm, (m, kind, name) => {
    names.push(name);
    return `${kind} ${name}`;
  })
  .replace(/^export\b/m, () => {
    console.error('build-mixmath: an export form the transform does not know. Use `export function` or `export var`.');
    process.exit(1);
  });

const out = `'use strict';

/**
 * GENERATED by scripts/build-mixmath.mjs from ${SRC}. Do NOT edit by hand.
 * Run the generator and commit the result, or the --check gate reports STALE.
 *
 * The custom mix arithmetic, server side: the same cents the console showed
 * the partner, sealed by the same function. lib/bids.js readBid() validates a
 * mix through checkMix() and seals tierSnapshot() per tier; nothing
 * downstream re-derives a cent.
 */

${body.replace(/^\/\*[\s\S]*?\*\/\n\n/, '')}
module.exports = {
  ${names.join(', ')}
};
`;

if (check) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (current !== out) {
    console.error('build-mixmath: STALE\n');
    console.error('  catalyst-backend/functions/auth/src/lib/mixmath.js');
    console.error('\nRun: node scripts/build-mixmath.mjs, then commit the result.');
    process.exit(1);
  }
  console.log(`build-mixmath: OK, ${names.length} exports`);
} else {
  writeFileSync(OUT, out);
  console.log('build-mixmath: wrote catalyst-backend/functions/auth/src/lib/mixmath.js');
  console.log(`  ${names.length} exports: ${names.join(', ')}`);
}
